export enum EffectTriggerType {
  ABOUT_TO_PLAY_CARD = "about_to_play_card",
  ATTACK = "attack",
  BETWEEN_TURNS = "between_turns",
  BUY = "buy",
  BUY_START = "buy_start",
  BUY_END = "buy_end",
  CLEANUP_START = "cleanup_start",
  DISCARD = "discard",
  FIRST_MADE_COINS = "first_made_coins",
  GAIN = "gain",
  INITIAL_SHUFFLE = "initial_shuffle",
  OTHER_GAIN = "other_gain",
  OTHER_PLAYED_CARD = "other_played_card",
  PLAYED_CARD = "played_card",
  REVEAL = "reveal",
  REVEALED_ACTION_DURING_DTX = "revealed_action_during_dtx",
  SHUFFLE = "shuffle",
  SUPPLY_PILE_EMPTIED = "SUPPLY_PILE_EMPTIED",
  TRASH = "trash",
  TURN_START = "turn_start",
  TURN_END = "turn_end",
  WOULD_GAIN = "would_gain",
  WOULD_SHUFFLE = "would_shuffle",
  NEVER = "never",
}
