export enum Expansion {
  BASE = 'Dominion',
  INTRIGUE = 'Intrigue',
  SEASIDE = 'Seaside',
  ALCHEMY = 'Alchemy',
  PROSPERITY = 'Prosperity',
  CORNUCOPIA_AND_GUILDS = 'Cornucopia and Guilds',
  CORNUCOPIA = 'Cornucopia',
  HINTERLANDS = 'Hinterlands',
  DARK_AGES = 'Dark Ages',
  GUILDS = 'Guilds',
  PROMO = 'Promo',
  ADVENTURES = 'Adventures',
  EMPIRES = 'Empires',
  NOCTURNE = 'Nocturne',
  RENAISSANCE = 'Renaissance',
  MENAGERIE = 'Menagerie',
  ALLIES = 'Allies',
  PLUNDER = 'Plunder',
  TESTING = 'Testing',
}
