import { CardCategory, CardInfo, CardType, Expansion, Mechanic } from '@dominion/common';

export const adventures: CardInfo[] = [
  {
    category: CardCategory.CARD,
    name: 'Amulet',
    text: 'Now and at the start of your next turn, choose one:\n+ $1 ; or trash a card from your hand; or gain a Silver.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Artificer',
    text: '+1 Card\n+1 Action\n+ $1 Discard any number of cards. You may gain a card onto your deck, costing exactly $1 per card discarded.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Bridge Troll',
    text: 'Each other player takes their – $1 token. On this turn and your next turn, cards cost $1 less. Now and at the start of your next turn:\n+1 Buy .',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION, CardType.ATTACK],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Caravan Guard',
    text: '+1 Card\n+1 Action At the start of your next turn,\n+ $1 .',
    font_size: 'large',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.DURATION, CardType.REACTION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Coin of the Realm',
    text: '$1 Put this on your Tavern mat.',
    font_size: 'large',
    cost: {coins: 2},
    types: [CardType.TREASURE, CardType.RESERVE],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Distant Lands',
    text: 'Put this on your Tavern mat.',
    font_size: 'xlarge',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.RESERVE, CardType.VICTORY],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Dungeon',
    text: '+1 Action Now and at the start of your next turn:\n+2 Cards , then discard 2 cards.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Duplicate',
    text: 'Put this on your Tavern mat.',
    font_size: 'xlarge',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.RESERVE],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Gear',
    text: '+2 Cards Set aside up to 2 cards from your hand face down (under this).\nAt the start of your next turn, put them into your hand.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Giant',
    text: 'Turn your Journey token over (it starts face up). Then if it\'s face down,\n+ $1 .\nIf it\'s face up,\n+ $5 , and each other player reveals the top card of their deck, trashes it if it costs from $3 to $6 , and otherwise discards it and gains a Curse.',
    font_size: 'small',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Guide',
    text: '+1 Card\n+1 Action Put this on your Tavern mat.',
    font_size: 'large',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.RESERVE],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Haunted Woods',
    text: 'At the start of your next turn:\n+3 Cards .\nUntil then, when any other player gains a card they bought, they put their hand onto their deck in any order.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION, CardType.ATTACK],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Hireling',
    text: 'At the start of each of your turns for the rest of the game:\n+1 Card .',
    font_size: 'medium',
    cost: {coins: 6},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Lost City',
    text: '+2 Cards\n+2 Actions',
    font_size: 'xlarge',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Magpie',
    text: '+1 Card\n+1 Action Reveal the top card of your deck.\nIf it\'s a Treasure, put it into your hand.\nIf it\'s an Action or Victory card, gain a Magpie.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Messenger',
    text: '+1 Buy\n+ $2 You may put your deck into your discard pile.',
    font_size: 'large',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Miser',
    text: 'Choose one: Put a Copper from your hand onto your Tavern mat; or\n+ $1 per Copper on your Tavern mat.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Page',
    text: '+1 Card\n+1 Action',
    font_size: 'xlarge',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.TRAVELLER],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Peasant',
    text: '+1 Buy\n+ $1',
    font_size: 'xxlarge',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.TRAVELLER],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Port',
    text: '+1 Card\n+2 Actions',
    font_size: 'xlarge',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Ranger',
    text: '+1 Buy Turn your Journey token over (it starts face up). Then if it\'s face up,\n+5 Cards .',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Ratcatcher',
    text: '+1 Card\n+1 Action Put this on your Tavern mat.',
    font_size: 'large',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.RESERVE],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Raze',
    text: '+1 Action Trash this or a card from your hand. Look at one card from the top of your deck per $1 the trashed card costs. Put one of them into your hand and discard the rest.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.ACTION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Relic',
    text: '$2 Each other player puts their –1 Card token on their deck.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.TREASURE, CardType.ATTACK],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Royal Carriage',
    text: '+1 Action Put this on your Tavern mat.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.RESERVE],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Storyteller',
    text: '+1 Action Play up to 3 Treasures from your hand. Then\n+1 Card , and pay all of your $ for\n+1 Card per $1 you paid.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Swamp Hag',
    text: 'At the start of your next turn:\n+ $3 .\nUntil then, when any other player gains a card they bought, they gain a Curse.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION, CardType.ATTACK],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Transmogrify',
    text: '+1 Action Put this on your Tavern mat.',
    font_size: 'large',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.RESERVE],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Treasure Trove',
    text: '$2 Gain a Gold and a Copper.',
    font_size: 'xlarge',
    cost: {coins: 5},
    types: [CardType.TREASURE],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Wine Merchant',
    text: '+1 Buy\n+ $4 Put this on your Tavern mat.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.RESERVE],
    expansion: Expansion.ADVENTURES,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Champion',
    text: '+1 Action For the rest of the game, when another player plays an Attack, it doesn\'t affect you, and when you play an Action card, you first get\n+1 Action . (This is not in the Supply.)',
    font_size: 'small',
    cost: {coins: 6, has_asterisk: true},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.CARD,
    name: 'Disciple',
    text: 'You may play an Action card from your hand twice. Gain a copy of it.',
    font_size: 'medium',
    cost: {coins: 5, has_asterisk: true},
    types: [CardType.ACTION, CardType.TRAVELLER],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.CARD,
    name: 'Fugitive',
    text: '+2 Cards\n+1 Action Discard a card.',
    font_size: 'large',
    cost: {coins: 4, has_asterisk: true},
    types: [CardType.ACTION, CardType.TRAVELLER],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.CARD,
    name: 'Hero',
    text: '+ $2 Gain a Treasure.',
    font_size: 'xlarge',
    cost: {coins: 5, has_asterisk: true},
    types: [CardType.ACTION, CardType.TRAVELLER],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.CARD,
    name: 'Soldier',
    text: '+ $2\n+ $1 per other Attack you have in play. Each other player with 4 or more cards in hand discards a card.',
    font_size: 'medium',
    cost: {coins: 3, has_asterisk: true},
    types: [CardType.ACTION, CardType.ATTACK, CardType.TRAVELLER],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.CARD,
    name: 'Teacher',
    text: 'Put this on your Tavern mat.',
    font_size: 'xlarge',
    cost: {coins: 6, has_asterisk: true},
    types: [CardType.ACTION, CardType.RESERVE],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.CARD,
    name: 'Treasure Hunter',
    text: '+1 Action\n+ $1 Gain a Silver per card the player to your right gained in their last turn.',
    font_size: 'medium',
    cost: {coins: 3, has_asterisk: true},
    types: [CardType.ACTION, CardType.TRAVELLER],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.CARD,
    name: 'Warrior',
    text: '+2 Cards For each Traveller you have in play (including this), each other player discards the top card of their deck and trashes it if it costs $3 or $4 .',
    font_size: 'medium',
    cost: {coins: 4, has_asterisk: true},
    types: [CardType.ACTION, CardType.ATTACK, CardType.TRAVELLER],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Alms',
    text: 'Once per turn: If you have no Treasures in play, gain a card costing up to $4 .',
    font_size: 'medium',
    cost: {coins: 0},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Ball',
    text: 'Take your – $1 token. Gain 2 cards each costing up to $4 .',
    font_size: 'large',
    cost: {coins: 5},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Bonfire',
    text: 'Trash up to 2 Coppers you have in play.',
    font_size: 'large',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Borrow',
    text: 'Once per turn:\n+1 Buy .\nIf your –1 Card token isn\'t on your deck, put it there and\n+ $1 .',
    font_size: 'medium',
    cost: {coins: 0},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Expedition',
    text: 'Draw 2 extra cards for your next hand.',
    font_size: 'large',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Ferry',
    text: 'Move your – $2 token to an Action Supply pile. (Cards from that pile cost $2 less on your turns.)',
    font_size: 'medium',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Inheritance',
    text: 'Once per game: Set aside a non-Command non-Duration Action card from the Supply costing up to $4 . Move your Estate token to it. (During your turns, Estates are also Command Actions with "Play the card with your Estate token, leaving it there.")',
    font_size: 'small',
    cost: {coins: 7},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Lost Arts',
    text: 'Move your\n+1 Action token to an Action Supply pile. (When you play a card from that pile, you first get\n+1 Action .)',
    font_size: 'medium',
    cost: {coins: 6},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Mission',
    text: 'Take an extra turn after this one (but not a 3rd turn in a row), during which you can\'t buy cards. (You can still buy Events.)',
    font_size: 'medium',
    cost: {coins: 4},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Pathfinding',
    text: 'Move your\n+1 Card token to an Action Supply pile. (When you play a card from that pile, you first get\n+1 Card .)',
    font_size: 'medium',
    cost: {coins: 8},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Pilgrimage',
    text: 'Once per turn: Turn your Journey token over (it starts face up); then if it\'s face up, choose up to 3 differently named cards you have in play and gain a copy of each.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Plan',
    text: 'Move your Trashing token to an Action Supply pile. (When you gain a card from that pile, you may trash a card from your hand.)',
    font_size: 'medium',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Quest',
    text: 'You may discard an Attack, two Curses, or six cards.\nIf you do, gain a Gold.',
    font_size: 'medium',
    cost: {coins: 0},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Raid',
    text: 'Gain a Silver per Silver you have in play. Each other player puts their –1 Card token on their deck.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Save',
    text: 'Once per turn:\n+1 Buy . Set aside a card from your hand, and put it into your hand at end of turn (after drawing).',
    font_size: 'medium',
    cost: {coins: 1},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Scouting Party',
    text: '+1 Buy Look at the top 5 cards of your deck. Discard 3 and put the rest back in any order.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Seaway',
    text: 'Gain an Action card costing up to $4 . Move your\n+1 Buy token to its pile. (When you play a card from that pile, you first get\n+1 Buy .)',
    font_size: 'medium',
    cost: {coins: 5},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Trade',
    text: 'Trash up to 2 cards from your hand. Gain a Silver per card you trashed.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Training',
    text: 'Move your\n+ $1 token to an Action Supply pile. (When you play a card from that pile, you first get\n+ $1 .)',
    font_size: 'medium',
    cost: {coins: 6},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
  {
    category: CardCategory.EVENT,
    name: 'Travelling Fair',
    text: '+2 Buys When you gain a card this turn, you may put it onto your deck.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [],
    expansion: Expansion.ADVENTURES,
    is_kingdom: false,
  },
];