import { CardCategory, CardInfo, CardType, Expansion, Mechanic } from '@dominion/common';

export const allies: CardInfo[] = [
  {
    name: 'Acolyte',
    category: CardCategory.CARD,
    text: 'You may trash an Action or Victory card from your hand to gain a Gold. You may trash this to gain an Augur.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION, CardType.AUGUR],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Archer',
    category: CardCategory.CARD,
    text: '+ $2 Each other player with 5 or more cards in hand reveals all but one, and discards one of those you choose.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION, CardType.ATTACK, CardType.CLASH],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Barbarian',
    category: CardCategory.CARD,
    text: '+ $2 Each other player trashes the top card of their deck.\nIf it costs $3 or more they gain a cheaper card sharing a type with it; otherwise they gain a Curse.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Battle Plan',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action You may reveal an Attack card from your hand for\n+1 Card . You may rotate any Supply pile.',
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.CLASH],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Bauble',
    category: CardCategory.CARD,
    text: 'Choose two different options:\n+1 Buy ;\n+ $1 ;\n+1 Favor ; this turn, when you gain a card, you may put it onto your deck.',
    font_size: 'medium',
    cost: { coins: 2 },
    types: [CardType.TREASURE, CardType.LIAISON],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Blacksmith',
    category: CardCategory.CARD,
    text: 'Choose one: Draw until you have 6 cards in hand; or\n+2 Cards ; or\n+1 Card and\n+1 Action .',
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.TOWNSFOLK],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Broker',
    category: CardCategory.CARD,
    text: 'Trash a card from your hand and choose one:\n+1 Card per $1 it costs; or\n+1 Action per $1 it costs; or\n+ $1 per $1 it costs; or\n+1 Favor per $1 it costs.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION, CardType.LIAISON],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Capital City',
    category: CardCategory.CARD,
    text: '+1 Card\n+2 Actions You may discard 2 cards for\n+ $2 . You may pay $2 for\n+2 Cards .',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Carpenter',
    category: CardCategory.CARD,
    text: 'If no Supply piles are empty,\n+1 Action and gain a card costing up to $4 . Otherwise, trash a card from your hand and gain a card costing up to $2 more than it.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Conjurer',
    category: CardCategory.CARD,
    text: 'Gain a card costing up to $4 .\nAt the start of your next turn, put this into your hand.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION, CardType.DURATION, CardType.WIZARD],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Contract',
    category: CardCategory.CARD,
    text: '$2\n+1 Favor You may set aside an Action from your hand to play it at the start of your next turn.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.TREASURE, CardType.DURATION, CardType.LIAISON],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Courier',
    category: CardCategory.CARD,
    text: '+ $1 Discard the top card of your deck. Look through your discard pile; you may play an Action or Treasure from it.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Distant Shore',
    category: CardCategory.CARD,
    text: '+2 Cards\n+1 Action Gain an Estate.',
    font_size: 'large',
    cost: { coins: 6 },
    types: [CardType.ACTION, CardType.VICTORY, CardType.ODYSSEY],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Elder',
    category: CardCategory.CARD,
    text: '+ $2 You may play an Action card from your hand.\nWhen it gives you a choice of abilities (with "choose") this turn, you may choose an extra (different) option.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.TOWNSFOLK],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Emissary',
    category: CardCategory.CARD,
    text: '+3 Cards If this made you shuffle (at least one card),\n+1 Action and\n+2 Favors .',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.LIAISON],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Galleria',
    category: CardCategory.CARD,
    text: '+ $3 This turn, when you gain a card costing $3 or $4 ,\n+1 Buy .',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Garrison',
    category: CardCategory.CARD,
    text: '+ $2 This turn, when you gain a card, add a token here.\nAt the start of your next turn, remove them for\n+1 Card each.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION, CardType.DURATION, CardType.FORT],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Guildmaster',
    category: CardCategory.CARD,
    text: '+ $3 This turn, when you gain a card,\n+1 Favor .',
    font_size: 'large',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.LIAISON],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Herb Gatherer',
    category: CardCategory.CARD,
    text: '+1 Buy Put your deck into your discard pile. Look through it and you may play a Treasure from it. You may rotate the Augurs.',
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.AUGUR],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Highwayman',
    category: CardCategory.CARD,
    text: 'At the start of your next turn, discard this from play and\n+3 Cards .\nUntil then, the first Treasure each other player plays each turn does nothing.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.DURATION, CardType.ATTACK],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Hill Fort',
    category: CardCategory.CARD,
    text: 'Gain a card costing up to $4 . Choose one: Put it into your hand; or\n+1 Card and\n+1 Action .',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.FORT],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Hunter',
    category: CardCategory.CARD,
    text: '+1 Action Reveal the top 3 cards of your deck. From those cards, put an Action, a Treasure, and a Victory card into your hand. Discard the rest.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Importer',
    category: CardCategory.CARD,
    text: 'At the start of your next turn, gain a card costing up to $5 .',
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.DURATION, CardType.LIAISON],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Innkeeper',
    category: CardCategory.CARD,
    text: '+1 Action Choose one:\n+1 Card ; or\n+3 Cards , then discard 3 cards; or\n+5 Cards , then discard 6 cards.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Lich',
    category: CardCategory.CARD,
    text: '+6 Cards\n+2 Actions Skip a turn.',
    font_size: 'large',
    cost: { coins: 6 },
    types: [CardType.ACTION, CardType.WIZARD],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Marquis',
    category: CardCategory.CARD,
    text: '+1 Buy\n+1 Card per card in your hand. Discard down to 10 cards in hand.',
    font_size: 'medium',
    cost: { coins: 6 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Merchant Camp',
    category: CardCategory.CARD,
    text: '+2 Actions\n+ $1',
    font_size: 'xlarge',
    cost: { coins: 3 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Miller',
    category: CardCategory.CARD,
    text: '+1 Action Look at the top 4 cards of your deck. Put one into your hand and discard the rest.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION, CardType.TOWNSFOLK],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Modify',
    category: CardCategory.CARD,
    text: 'Trash a card from your hand. Choose one:\n+1 Card and\n+1 Action ; or gain a card costing up to $2 more than the trashed card.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Old Map',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action Discard a card.\n+1 Card . You may rotate the Odysseys.',
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.ODYSSEY],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Royal Galley',
    category: CardCategory.CARD,
    text: "+1 Card You may play a non-Duration Action card from your hand. Don't discard it in Clean-up until your next turn.\nAt the start of your next turn, if it's still in play, replay it.",
    font_size: 'small',
    cost: { coins: 4 },
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Sentinel',
    category: CardCategory.CARD,
    text: 'Look at the top 5 cards of your deck. You may trash up to 2 of them. Put the rest back in any order.',
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Sibyl',
    category: CardCategory.CARD,
    text: '+4 Cards\n+1 Action Put a card from your hand on top of your deck, and another on the bottom.',
    font_size: 'medium',
    cost: { coins: 6 },
    types: [CardType.ACTION, CardType.AUGUR],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Skirmisher',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n+ $1 This turn, when you gain an Attack card, each other player discards down to 3 cards in hand.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Sorcerer',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action Each other player names a card, then reveals the top card of their deck.\nIf wrong, they gain a Curse.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.ATTACK, CardType.WIZARD],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Sorceress',
    category: CardCategory.CARD,
    text: "+1 Action Name a card. Reveal the top card of your deck and put it into your hand.\nIf it's the named card, each other player gains a Curse.",
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.ATTACK, CardType.AUGUR],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Specialist',
    category: CardCategory.CARD,
    text: 'You may play an Action or Treasure from your hand. Choose one: Play it again; or gain a copy of it.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Stronghold',
    category: CardCategory.CARD,
    text: 'Choose one:\n+ $3 ; or at the start of your next turn,\n+3 Cards .',
    font_size: 'medium',
    cost: { coins: 6 },
    types: [CardType.ACTION, CardType.VICTORY, CardType.DURATION, CardType.FORT],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Student',
    category: CardCategory.CARD,
    text: "+1 Action You may rotate the Wizards. Trash a card from your hand.\nIf it's a Treasure,\n+1 Favor and put this onto your deck.",
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.WIZARD, CardType.LIAISON],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Sunken Treasure',
    category: CardCategory.CARD,
    text: "Gain an Action card you don't have a copy of in play.",
    font_size: 'large',
    cost: { coins: 5 },
    types: [CardType.TREASURE, CardType.ODYSSEY],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Swap',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action You may return an Action from your hand to its pile, to gain to your hand a different Action costing up to $5 .',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Sycophant',
    category: CardCategory.CARD,
    text: '+1 Action Discard 3 cards.\nIf you discarded at least one,\n+ $3 .',
    font_size: 'medium',
    cost: { coins: 2 },
    types: [CardType.ACTION, CardType.LIAISON],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Tent',
    category: CardCategory.CARD,
    text: '+ $2 You may rotate the Forts.',
    font_size: 'large',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.FORT],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Territory',
    category: CardCategory.CARD,
    text: 'Worth 1 per differently named Victory card you have.',
    font_size: 'large',
    cost: { coins: 6 },
    types: [CardType.VICTORY, CardType.CLASH],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Town',
    category: CardCategory.CARD,
    text: 'Choose one:\n+1 Card and\n+2 Actions ; or\n+1 Buy and\n+ $2 .',
    font_size: 'large',
    cost: { coins: 4 },
    types: [CardType.ACTION],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Town Crier',
    category: CardCategory.CARD,
    text: 'Choose one:\n+ $2 ; or gain a Silver; or\n+1 Card and\n+1 Action . You may rotate the Townsfolk.',
    font_size: 'medium',
    cost: { coins: 2 },
    types: [CardType.ACTION, CardType.TOWNSFOLK],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Underling',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n+1 Favor',
    font_size: 'xlarge',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.LIAISON],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Voyage',
    category: CardCategory.CARD,
    text: '+1 Action Take an extra turn after this one (but not a 3rd turn in a row), during which you can only play 3 cards from your hand.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION, CardType.DURATION, CardType.ODYSSEY],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: 'Warlord',
    category: CardCategory.CARD,
    text: "+1 Action At the start of your next turn,\n+2 Cards .\nUntil then, other players can't play an Action from their hand that they have 2 or more copies of in play.",
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.DURATION, CardType.ATTACK, CardType.CLASH],
    expansion: Expansion.ALLIES,
    is_kingdom: true,
  },
  {
    name: "Architects' Guild",
    category: CardCategory.ALLY,
    text: 'When you gain a card, you may spend 2 Favors to gain a cheaper non-Victory card.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Band of Nomads',
    category: CardCategory.ALLY,
    text: 'When you gain a card costing $3 or more, you may spend a Favor , for\n+1 Card , or\n+1 Action , or\n+1 Buy .',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Cave Dwellers',
    category: CardCategory.ALLY,
    text: 'At the start of your turn, you may spend a Favor , to discard a card then draw a card. Repeat as desired.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Circle of Witches',
    category: CardCategory.ALLY,
    text: 'After playing a Liaison, you may spend 3 Favors to have each other player gain a Curse.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'City-state',
    category: CardCategory.ALLY,
    text: 'When you gain an Action card during your turn, you may spend 2 Favors to play it.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Coastal Haven',
    category: CardCategory.ALLY,
    text: 'When discarding your hand in Clean-up, you may spend any number of Favors to keep that many cards in hand for next turn (you still draw 5).',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: "Crafters' Guild",
    category: CardCategory.ALLY,
    text: 'At the start of your turn, you may spend 2 Favors to gain a card costing up to $4 onto your deck.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Desert Guides',
    category: CardCategory.ALLY,
    text: 'At the start of your turn, you may spend a Favor to discard your hand and draw 5 cards. Repeat as desired.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Family of Inventors',
    category: CardCategory.ALLY,
    text: 'At the start of your Buy phase, you may put a Favor token you have on a non-Victory Supply pile. Cards cost $1 less per Favor token on their piles.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Fellowship of Scribes',
    category: CardCategory.ALLY,
    text: 'After playing an Action, if you have 4 or fewer cards in hand, you may spend a Favor for\n+1 Card .',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Forest Dwellers',
    category: CardCategory.ALLY,
    text: 'At the start of your turn, you may spend a Favor to look at the top 3 cards of your deck, discard any number and put the rest back in any order.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Gang of Pickpockets',
    category: CardCategory.ALLY,
    text: 'At the start of your turn, discard down to 4 cards in hand unless you spend a Favor .',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Island Folk',
    category: CardCategory.ALLY,
    text: 'At the end of your turn, you may spend 5 Favors to take an extra turn after this one (but not a 3rd turn in a row).',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'League of Bankers',
    category: CardCategory.ALLY,
    text: 'At the start of your Buy phase,\n+ $1 per 4 Favors you have (round down).',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'League of Shopkeepers',
    category: CardCategory.ALLY,
    text: 'After playing a Liaison, if you have 5 or more Favors ,\n+ $1 , and if 10 or more,\n+1 Action and\n+1 Buy .',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Market Towns',
    category: CardCategory.ALLY,
    text: 'At the start of your Buy phase, you may spend a Favor to play an Action card from your hand. Repeat as desired.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Mountain Folk',
    category: CardCategory.ALLY,
    text: 'At the start of your turn, you may spend 5 Favors for\n+3 Cards .',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Order of Astrologers',
    category: CardCategory.ALLY,
    text: 'When shuffling, you may pick one card per Favor you spend to go on top.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Order of Masons',
    category: CardCategory.ALLY,
    text: 'When shuffling, you may pick up to 2 cards per Favor you spend to put into your discard pile.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Peaceful Cult',
    category: CardCategory.ALLY,
    text: 'At the start of your Buy phase, you may spend any number of Favors to trash that many cards from your hand.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: 'Plateau Shepherds',
    category: CardCategory.ALLY,
    text: 'When scoring, pair up your Favors with cards you have costing $2 , for 2 per pair.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: "Trappers' Lodge",
    category: CardCategory.ALLY,
    text: 'When you gain a card, you may spend a Favor to put it onto your deck.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
  {
    name: "Woodworkers' Guild",
    category: CardCategory.ALLY,
    text: 'At the start of your Buy phase, you may spend a Favor to trash an Action card from your hand.\nIf you did, gain an Action card.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.ALLIES,
    is_kingdom: false,
  },
];
