import { CardCategory, CardInfo, CardType, Expansion } from '@dominion/common';

export const base_game: CardInfo[] = [
  {
    name: 'Artisan',
    category: CardCategory.CARD,
    text: 'Gain a card to your hand\ncosting up to $5.\n\nPut a card from your hand\nonto your deck.',
    font_size: 'medium',
    cost: {
      coins: 6,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Bandit',
    category: CardCategory.CARD,
    text: 'Gain a Gold. Each other\nplayer reveals the top 2 cards\nof their deck, trashes a revealed\nTreasure other than Copper,\nand discards the rest.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Bureaucrat',
    category: CardCategory.CARD,
    text: 'Gain a Silver onto your deck.\nEach other player reveals a\nVictory card from their hand\nand puts it onto their deck\n(or reveals a hand with no\nVictory cards).',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Cellar',
    category: CardCategory.CARD,
    text: '+1 Action\n\nDiscard any number of cards.\n+1 Card per card discarded.',
    font_size: 'medium',
    cost: {
      coins: 2,
    },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Chapel',
    category: CardCategory.CARD,
    text: 'Trash up to 4 cards\nfrom your hand.',
    font_size: 'medium',
    cost: {
      coins: 2,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Council Room',
    category: CardCategory.CARD,
    text: '+4 Cards\n+1 Buy\n\nEach other player draws a card.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Festival',
    category: CardCategory.CARD,
    text: '+2 Actions\n+1 Buy\n+$2',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Gardens',
    category: CardCategory.CARD,
    text: 'Worth 1VP per 10 cards you\nhave (round down).',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.VICTORY],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Harbinger',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n\nLook through your discard pile.\nYou may put a card from it\nonto your deck.',
    font_size: 'medium',
    cost: {
      coins: 3,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Laboratory',
    category: CardCategory.CARD,
    text: '+2 Cards\n+1 Action',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Library',
    category: CardCategory.CARD,
    text: 'Draw until you have 7 cards\nin hand, skipping any Action\ncards you choose to;\nset those aside, discarding\nthem afterwards.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Market',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n+1 Buy\n+$1',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Merchant',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n\nThe first time you play a Silver this turn, +$1.',
    font_size: 'medium',
    cost: {
      coins: 3,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Militia',
    category: CardCategory.CARD,
    text: '+$2\n\nEach other player discards down to 3 cards in hand.',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Mine',
    category: CardCategory.CARD,
    text: 'You may trash a Treasure from\nyour hand. Gain a Treasure to\nyour hand costing up to $3\nmore than it.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Moat',
    category: CardCategory.CARD,
    text: '+2 Cards\n-\nWhen another player plays\nan Attack card, you may first\nreveal this from your hand, to\nbe unaffected by it.',
    font_size: 'medium',
    cost: {
      coins: 2,
    },
    types: [CardType.ACTION, CardType.REACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Moneylender',
    category: CardCategory.CARD,
    text: 'You may trash a Copper from\nyour hand for +$3.',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Poacher',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n+$1\n\nDiscard a card per empty\nSupply pile.',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Remodel',
    category: CardCategory.CARD,
    text: 'Trash a card from your hand.\nGain a card costing up to\n$2 more than it.',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Sentry',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n\nLook at the top 2 cards of your\ndeck. Trash and/or discard any\nnumber of them. Put the rest\nback on top in any order.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Smithy',
    category: CardCategory.CARD,
    text: '+3 Cards',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Throne Room',
    category: CardCategory.CARD,
    text: 'You may play an Action card\nfrom your hand twice.',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Vassal',
    category: CardCategory.CARD,
    text: "+$2\n\nDiscard the top card of your\ndeck. If it's an Action card,\nyou may play it.",
    font_size: 'medium',
    cost: {
      coins: 3,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Village',
    category: CardCategory.CARD,
    text: '+1 Card\n+2 Actions',
    font_size: 'medium',
    cost: {
      coins: 3,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Witch',
    category: CardCategory.CARD,
    text: '+2 Cards\n\nEach other player\ngains a Curse.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
  {
    name: 'Workshop',
    category: CardCategory.CARD,
    text: 'Gain a card costing up to $4.',
    font_size: 'medium',
    cost: {
      coins: 3,
    },
    types: [CardType.ACTION],
    expansion: Expansion.BASE,
    has_randomizer: true,
  },
];
