import { CardCategory, CardInfo, CardType, Expansion, Mechanic } from '@dominion/common';

export const cornucopiaAndGuilds: CardInfo[] = [
  {
    name: 'Hamlet',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\nYou may discard a card\nfor +1 Action.\nYou may discard a card\nfor +1 Buy.',
    font_size: 'medium',
    cost: {
      coins: 2,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Menagerie',
    category: CardCategory.CARD,
    text: '+1 Action\n\nReveal your hand.\nIf the revealed cards all have\ndifferent names, +3 Cards.\nOtherwise, +1 Card.',
    font_size: 'medium',
    cost: {
      coins: 3,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Remake',
    category: CardCategory.CARD,
    text: 'Do this twice: Trash a card\nfrom your hand, then gain\na card costing exactly $1 more than it.',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Young Witch',
    category: CardCategory.CARD,
    text: '+2 Cards\nDiscard 2 cards. Each other player\ngains a Curse unless they reveal a\nBane from their hand.\n-\nSetup: Add an extra Kingdom\ncard pile costing $2 or $3 to the\nSupply. Its cards are Banes.',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Horn of Plenty',
    category: CardCategory.CARD,
    text: "Gain a card costing up to\n$1 per differently named card\nyou have in play (counting\nthis). If it's a Victory card,\ntrash this.",
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.TREASURE],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Hunting Party',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\nReveal your hand. Reveal cards\nfrom your deck until you reveal\na card that isn’t a copy of one\nin your hand. Put it into your\nhand and discard the rest.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Jester',
    category: CardCategory.CARD,
    text: '+$2\nEach other player discards\nthe top card of their deck.\nIf it’s a Victory card they\ngain a Curse; otherwise they\ngain a copy of the discarded\ncard or you do, your choice.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Fairgrounds',
    category: CardCategory.CARD,
    text: 'Worth 2 VP per 5\ndifferently named cards you\nhave (round down).',
    font_size: 'medium',
    cost: {
      coins: 6,
    },
    types: [CardType.VICTORY],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Candlestick Maker',
    category: CardCategory.CARD,
    text: '+1 Action\n+1 Buy\n+1 Coffers',
    font_size: 'medium',
    cost: {
      coins: 2,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    mechanics: [Mechanic.COFFERS],
    is_kingdom: true,
  },
  {
    name: 'Stonemason',
    category: CardCategory.CARD,
    text: 'Trash a card from your hand.\nGain 2 cards each costing\nless than it.\n-\nOverpay: Gain 2 Action\ncards each costing the\namount overpaid.',
    font_size: 'medium',
    cost: {
      coins: 2,
      has_plus: true,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Advisor',
    category: CardCategory.CARD,
    text: '+1 Action\n\nReveal the top 3 cards of\nyour deck. The player to\nyour left chooses one of\nthem. Discard that card and\nput the rest into your hand.',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Herald',
    category: CardCategory.CARD,
    text: "+1 Card\n+1 Action\nReveal the top card of your\ndeck. If it's an Action, play it.\n-\nOverpay: Per $1 overpaid,\nput any card from your discard\npile onto your deck.",
    font_size: 'medium',
    cost: {
      coins: 4,
      has_plus: true,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Plaza',
    category: CardCategory.CARD,
    text: '+1 Card\n+2 Actions\n\nYou may discard a Treasure\nfor +1 Coffers.',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    mechanics: [Mechanic.COFFERS],
    is_kingdom: true,
  },
  {
    name: 'Baker',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n+1 Coffers\n-\nSetup: Each player gets\n+1 Coffers.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    mechanics: [Mechanic.COFFERS],
    is_kingdom: true,
  },
  {
    name: 'Butcher',
    category: CardCategory.CARD,
    text: '+2 Coffers\n\nYou may trash a card from your\nhand, to gain a card, costing\nup to $1 more than it per\nCoffers you spend.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    mechanics: [Mechanic.COFFERS],
    is_kingdom: true,
  },
  {
    name: 'Journeyman',
    category: CardCategory.CARD,
    text: 'Name a card. Reveal cards\nfrom your deck until you\nreveal 3 cards without that\nname. Put those cards into\nyour hand and discard the rest.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Merchant Guild',
    category: CardCategory.CARD,
    text: '+1 Buy\n+$1\n\nAt the end of your Buy phase\nthis turn, +1 Coffers per card\nyou gained in it.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    mechanics: [Mechanic.COFFERS],
    is_kingdom: true,
  },
  {
    name: 'Soothsayer',
    category: CardCategory.CARD,
    text: 'Gain a Gold. Each other\nplayer gains a Curse, and if\nthey did, draws a card.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Farrier',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n+1 Buy\n-\nOverpay: +1 Card at the end\nof this turn per $1 overpaid.',
    font_size: 'medium',
    cost: {
      coins: 3,
      has_plus: true,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Shop',
    category: CardCategory.CARD,
    text: "+1 Card\n+$1\nYou may play an Action card\nfrom your hand that you don't\nhave a copy of in play.",
    font_size: 'medium',
    cost: {
      coins: 3,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Infirmary',
    category: CardCategory.CARD,
    text: '+1 Card\nYou may trash a card\nfrom your hand.\n-\nOverpay: Play this once\nper $1 overpaid.',
    font_size: 'medium',
    cost: {
      coins: 3,
      has_plus: true,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Farmhands',
    category: CardCategory.CARD,
    text: '+1 Card\n+2 Action\n-\nWhen you gain this, you may\nset aside an Action or Treasure\nfrom your hand, and play it at\nthe start of your next turn.',
    font_size: 'medium',
    cost: {
      coins: 4,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Carnival',
    category: CardCategory.CARD,
    text: 'Reveal the top 4 cards of\nyour deck. Put one of each\ndifferently named card into\nyour hand and discard the rest.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Ferryman',
    category: CardCategory.CARD,
    text: '+2 Cards\n+1 Action\nDiscard a card\n-\nSetup: Choose an unused\nKingdom card pile costing\n$3 or $4.Gain one when\nyou gain a Ferryman.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: true,
  },
  {
    name: 'Footpad',
    category: CardCategory.CARD,
    text: '+2 Coffers\nEach other player discards\ndown to 3 cards in hand.\n-\nIn games using this,\nwhen you gain a card in an\nAction phase, +1 Card.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    mechanics: [Mechanic.COFFERS],
    is_kingdom: true,
  },
  {
    name: 'Joust',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n+$1\nYou may set aside a Province\nfrom your hand to gain any\nReward to your hand. Discard\nthe Province in Clean-up.',
    font_size: 'medium',
    cost: {
      coins: 5,
    },
    types: [CardType.ACTION],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    mechanics: [Mechanic.COFFERS],
    is_kingdom: true,
  },
  {
    name: 'Coronet',
    category: CardCategory.CARD,
    text: 'You may play a non-Reward\nAction from your hand twice.\n\nYou may play a non-Reward\nTreasure from your hand twice.\n\n(This is not in the Supply.)',
    font_size: 'medium',
    cost: {
      coins: 0,
      has_asterisk: true,
    },
    types: [CardType.ACTION, CardType.TREASURE, CardType.REWARD],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: false,
  },
  {
    name: 'Courser',
    category: CardCategory.CARD,
    text: 'Choose two different options:\n+2 Cards; +2 Actions;\n+$2; gain 4 Silvers.\n\n(This is not in the Supply.)',
    font_size: 'medium',
    cost: {
      coins: 0,
      has_asterisk: true,
    },
    types: [CardType.ACTION, CardType.REWARD],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: false,
  },
  {
    name: 'Demesne',
    category: CardCategory.CARD,
    text: '+2 Actions\n+2 Buys\nGain a Gold.\n-\nWorth 1 VP per Gold you have.\n(This is not in the Supply.)',
    font_size: 'medium',
    cost: {
      coins: 0,
      has_asterisk: true,
    },
    types: [CardType.ACTION, CardType.VICTORY, CardType.REWARD],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: false,
  },
  {
    name: 'Housecarl',
    category: CardCategory.CARD,
    text: '+1 Card per differently named\nAction card you have in play.\n\n(This is not in the Supply.)',
    font_size: 'medium',
    cost: {
      coins: 0,
      has_asterisk: true,
    },
    types: [CardType.ACTION, CardType.REWARD],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: false,
  },
  {
    name: 'Huge Turnip',
    category: CardCategory.CARD,
    text: '+2 Coffers\n\n+$1 per Coffers you have.\n\n(This is not in the Supply.)',
    font_size: 'medium',
    cost: {
      coins: 0,
      has_asterisk: true,
    },
    production: {
      is_variable: true,
    },
    types: [CardType.TREASURE, CardType.REWARD],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    mechanics: [Mechanic.COFFERS],
    is_kingdom: false,
  },
  {
    name: 'Renown',
    category: CardCategory.CARD,
    text: '+1 Buy\n\nThis turn, cards cost $2 less.\n(This is not in the Supply.)',
    font_size: 'medium',
    cost: {
      coins: 0,
      has_asterisk: true,
    },
    types: [CardType.ACTION, CardType.REWARD],
    expansion: Expansion.CORNUCOPIA_AND_GUILDS,
    is_kingdom: false,
  },
];
