import { CardCategory, CardInfo, CardType, Expansion, Mechanic } from '@dominion/common';

export const deprecated: CardInfo[] = [
  {
    category: CardCategory.CARD,
    name: 'Adventurer',
    text: 'Reveal cards from your deck until you reveal 2 Treasure cards. Put those Treasure cards into your hand and discard the other revealed cards.',
    font_size: 'medium',
    cost: {coins: 6},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Chancellor',
    text: '+ $2 You may immediately put your deck into your discard pile.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Feast',
    text: 'Trash this card. Gain a card costing up to $5 .',
    font_size: 'large',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Spy',
    text: '+1 Card\n+1 Action Each player (including you) reveals the top card of their deck and either discards it or puts it back, your choice.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Thief',
    text: 'Each other player reveals the top 2 cards of their deck.\nIf they revealed any Treasure cards, they trash one of them that you choose. You may gain any or all of these trashed cards. They discard the other revealed cards.',
    font_size: 'small',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Woodcutter',
    text: '+1 Buy\n+ $2',
    font_size: 'xxlarge',
    cost: {coins: 3},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Doctor',
    text: 'Name a card. Reveal the top 3 cards of your deck. Trash the matches. Put the rest back in any order.',
    font_size: 'medium',
    cost: {coins: 3, has_plus: true},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Farming Village',
    text: '+2 Actions Reveal cards from your deck until you reveal a Treasure or Action card. Put that card into your hand and discard the rest.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Fortune Teller',
    text: '+ $2 Each other player reveals cards from the top of their deck until they reveal a Victory card or a Curse. They put it on top and discard the rest.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Harvest',
    text: 'Reveal the top 4 cards of your deck, then discard them.\n+ $1 per differently named card revealed.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Horse Traders',
    text: '+1 Buy\n+ $3 Discard 2 cards.',
    font_size: 'xlarge',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.REACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Masterpiece',
    text: '$1',
    font_size: 'xxlarge',
    cost: {coins: 3, has_plus: true},
    types: [CardType.TREASURE],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Taxman',
    text: 'You may trash a Treasure from your hand. Each other player with 5 or more cards in hand discards a copy of it (or reveals they can\'t). Gain a Treasure onto your deck costing up to $3 more than it.',
    font_size: 'small',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Tournament',
    text: '+1 Action Each player may reveal a Province from their hand.\nIf you do, discard it and gain any Prize (from the Prize pile) or a Duchy, onto your deck.\nIf no-one else does,\n+1 Card and\n+ $1 .',
    font_size: 'small',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Bag of Gold',
    text: '+1 Action Gain a Gold onto your deck. (This is not in the Supply.)',
    font_size: 'medium',
    cost: {coins: 0, has_asterisk: true},
    types: [CardType.ACTION, CardType.REWARD],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Diadem',
    text: '$2\n+ $1 per unused Action you have (Action, not Action card). (This is not in the Supply.)',
    font_size: 'medium',
    cost: {coins: 0, has_asterisk: true},
    types: [CardType.TREASURE, CardType.REWARD],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Followers',
    text: '+2 Cards Gain an Estate. Each other player gains a Curse and discards down to 3 cards in hand. (This is not in the Supply.)',
    font_size: 'medium',
    cost: {coins: 0, has_asterisk: true},
    types: [CardType.ACTION, CardType.ATTACK, CardType.REWARD],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Princess',
    text: '+1 Buy This turn, cards cost $2 less. (This is not in the Supply.)',
    font_size: 'medium',
    cost: {coins: 0, has_asterisk: true},
    types: [CardType.ACTION, CardType.REWARD],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Trusty Steed',
    text: 'Choose two:\n+2 Cards ; or\n+2 Actions ; or\n+ $2 ; or gain 4 Silvers and put your deck into your discard pile. The choices must be different. (This is not in the Supply.)',
    font_size: 'medium',
    cost: {coins: 0, has_asterisk: true},
    types: [CardType.ACTION, CardType.REWARD],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Cache',
    text: '$3',
    font_size: 'xxlarge',
    cost: {coins: 5},
    types: [CardType.TREASURE],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Duchess',
    text: '+ $2 Each player (including you) looks at the top card of their deck and may discard it.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Embassy',
    text: '+5 Cards Discard 3 cards.',
    font_size: 'xlarge',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Ill-Gotten Gains',
    text: '$1 You may gain a Copper to your hand.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.TREASURE],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Mandarin',
    text: '+ $3 Put a card from your hand onto your deck.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Noble Brigand',
    text: '+ $1 Each other player reveals the top 2 cards of their deck, trashes a revealed Silver or Gold you choose, discards the rest, and gains a Copper if they didn\'t reveal a Treasure. You gain the trashed cards.',
    font_size: 'small',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Nomad Camp',
    text: '+1 Buy\n+ $2',
    font_size: 'xxlarge',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Oracle',
    text: 'Each player (including you) reveals the top 2 cards of their deck, and discards them or puts them back, your choice (they choose the order). Then,\n+2 Cards .',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Silk Road',
    text: 'Worth 1 for every 4 Victory cards you have (round down).',
    font_size: 'large',
    cost: {coins: 4},
    types: [CardType.VICTORY],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Coppersmith',
    text: 'Copper produces an extra $1 this turn.',
    font_size: 'large',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Great Hall',
    text: '+1 Card\n+1 Action',
    font_size: 'xlarge',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.VICTORY],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Saboteur',
    text: 'Each other player reveals cards from the top of their deck until revealing one costing $3 or more. They trash that card and may gain a card costing at most $2 less than it. They discard the other revealed cards.',
    font_size: 'small',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Scout',
    text: '+1 Action Reveal the top 4 cards of your deck. Put the revealed Victory cards into your hand. Put the other cards on top of your deck in any order.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Secret Chamber',
    text: 'Discard any number of cards.\n+ $1 per card discarded.',
    font_size: 'large',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.REACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Tribute',
    text: 'The player to your left reveals then discards the top 2 cards of their deck. For each differently named card revealed, if it is an… Action Card,\n+2 Actions Treasure Card,\n+ $2 Victory Card,\n+2 Cards',
    font_size: 'small',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Contraband',
    text: '$3\n+1 Buy The player to your left names a card. You can\'t buy that card this turn.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.TREASURE],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Counting House',
    text: 'Look through your discard pile, reveal any number of Coppers from it, and put them into your hand.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Goons',
    text: '+1 Buy\n+ $2 Each other player discards down to 3 cards in hand.',
    font_size: 'medium',
    cost: {coins: 6},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Loan',
    text: '$1 Reveal cards from your deck until you reveal a Treasure. Discard it or trash it. Discard the other cards.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.TREASURE],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Mountebank',
    text: '+ $2 Each other player may discard a Curse.\nIf they don\'t, they gain a Curse and a Copper.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Royal Seal',
    text: '$2',
    font_size: 'xxlarge',
    cost: {coins: 5},
    types: [CardType.TREASURE],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Talisman',
    text: '$1',
    font_size: 'xxlarge',
    cost: {coins: 4},
    types: [CardType.TREASURE],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Trade Route',
    text: '+1 Buy Trash a card from your hand.\n+ $1 per Coin token on the Trade Route mat.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Venture',
    text: '$1 Reveal cards from your deck until you reveal a Treasure. Discard the other cards. Play that Treasure.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.TREASURE],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Ambassador',
    text: 'Reveal a card from your hand. Return up to 2 copies of it from your hand to the Supply. Then each other player gains a copy of it.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Embargo',
    text: '+ $2 Trash this to add an Embargo token to a Supply pile. (For the rest of the game, when a player buys a card from that pile, they gain a Curse.)',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Explorer',
    text: 'You may reveal a Province from your hand.\nIf you do, gain a Gold to your hand.\nIf you don\'t, gain a Silver to your hand.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Ghost Ship',
    text: '+2 Cards Each other player with 4 or more cards in hand puts cards from their hand onto their deck until they have 3 cards in hand.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Navigator',
    text: '+ $2 Look at the top 5 cards of your deck. Either discard them all, or put them back in any order.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Pearl Diver',
    text: '+1 Card\n+1 Action Look at the bottom card of your deck. You may put it on top.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.ACTION],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Pirate Ship',
    text: 'Choose one:\n+ $1 per Coin token on your Pirate Ship mat; or each other player reveals the top 2 cards of their deck, trashes one of those Treasures that you choose, and discards the rest, and then if anyone trashed a Treasure, you add a Coin token to your Pirate Ship mat.',
    font_size: 'small',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Sea Hag',
    text: 'Each other player discards the top card of their deck, then gains a Curse onto their deck.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Harem',
    text: '$2 2',
    font_size: 'xxlarge',
    cost: {coins: 6},
    types: [CardType.TREASURE, CardType.VICTORY],
    expansion: Expansion.DEPRECATED,
    is_kingdom: true,
  },
];