import { CardCategory, CardInfo, CardType, Expansion, Mechanic } from '@dominion/common';

export const empires: CardInfo[] = [
  {
    name: 'Archive',
    category: CardCategory.CARD,
    text: '+1 Action Set aside the top 3 cards of your deck face down (you may look at them). Now and at the start of your next two turns, put one into your hand.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Bustling Village',
    category: CardCategory.CARD,
    text: '+1 Card\n+3 Actions You may reveal a Settlers from your discard pile and put it into your hand.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Capital',
    category: CardCategory.CARD,
    text: '$6\n+1 Buy',
    font_size: 'xxlarge',
    cost: { coins: 5 },
    types: [CardType.TREASURE],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Catapult',
    category: CardCategory.CARD,
    text: "+ $1 Trash a card from your hand.\nIf it costs $3 or more, each other player gains a Curse.\nIf it's a Treasure, each other player discards down to 3 cards in hand.",
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Chariot Race',
    category: CardCategory.CARD,
    text: '+1 Action\n+1 Card , revealing it. The player to your left reveals the top card of their deck.\nIf your card costs more,\n+ $1 and +1 .',
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Charm',
    category: CardCategory.CARD,
    text: 'Choose one:\n+1 Buy and\n+ $2 ; or the next time you gain a card this turn, you may also gain a differently named card with the same cost.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.TREASURE],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'City Quarter',
    category: CardCategory.CARD,
    text: '+2 Actions Reveal your hand.\n+1 Card per Action card revealed.',
    font_size: 'medium',
    cost: { coins: 0, debt: 8 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Crown',
    category: CardCategory.CARD,
    text: "If it's your Action phase, you may play an Action from your hand twice.\nIf it's your Buy phase, you may play a Treasure from your hand twice.",
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.TREASURE],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Crumbling Castle',
    category: CardCategory.CARD,
    text: '1',
    font_size: 'xxlarge',
    cost: { coins: 4 },
    types: [CardType.VICTORY, CardType.CASTLE],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Emporium',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n+ $1',
    font_size: 'xlarge',
    cost: { coins: 5 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Encampment',
    category: CardCategory.CARD,
    text: '+2 Cards\n+2 Actions You may reveal a Gold or Plunder from your hand.\nIf you do not, set this aside, and return it to its pile at the start of Clean-up.',
    font_size: 'medium',
    cost: { coins: 2 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Enchantress',
    category: CardCategory.CARD,
    text: 'Until your next turn, the first time each other player plays an Action card on their turn, they get\n+1 Card and\n+1 Action instead of following its instructions.\nAt the start of your next turn,\n+2 Cards',
    font_size: 'small',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.ATTACK, CardType.DURATION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Engineer',
    category: CardCategory.CARD,
    text: 'Gain a card costing up to $4 . You may trash this.\nIf you do, gain a card costing up to $4 .',
    font_size: 'medium',
    cost: { coins: 0, debt: 4 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: "Farmers' Market",
    category: CardCategory.CARD,
    text: "+1 Buy If there are 4 or more on the Farmers' Market pile, take them and trash this. Otherwise, add 1 to the pile and then\n+ $1 per 1 on the pile.",
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.GATHERING],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Fortune',
    category: CardCategory.CARD,
    text: "+1 Buy Double your $ if you haven't yet this turn.",
    font_size: 'large',
    cost: { coins: 8, debt: 8 },
    types: [CardType.TREASURE],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Forum',
    category: CardCategory.CARD,
    text: '+3 Cards\n+1 Action Discard 2 cards.',
    font_size: 'large',
    cost: { coins: 5 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Gladiator',
    category: CardCategory.CARD,
    text: "+ $2 Reveal a card from your hand. The player to your left may reveal a copy from their hand.\nIf they don't,\n+ $1 and trash a Gladiator from its pile.",
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Grand Castle',
    category: CardCategory.CARD,
    text: '5',
    font_size: 'xxlarge',
    cost: { coins: 9 },
    types: [CardType.VICTORY, CardType.CASTLE],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Groundskeeper',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action This turn, when you gain a Victory card, +1 .',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Haunted Castle',
    category: CardCategory.CARD,
    text: '2',
    font_size: 'xxlarge',
    cost: { coins: 6 },
    types: [CardType.VICTORY, CardType.CASTLE],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Humble Castle',
    category: CardCategory.CARD,
    text: '$1',
    font_size: 'xxlarge',
    cost: { coins: 3 },
    types: [CardType.TREASURE, CardType.VICTORY, CardType.CASTLE],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: "King's Castle",
    category: CardCategory.CARD,
    text: 'Worth 2 per Castle you have.',
    font_size: 'xlarge',
    cost: { coins: 10 },
    types: [CardType.VICTORY, CardType.CASTLE],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Legionary',
    category: CardCategory.CARD,
    text: '+ $3 You may reveal a Gold from your hand.\nIf you do, each other player discards down to 2 cards in hand, then draws a card.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Opulent Castle',
    category: CardCategory.CARD,
    text: 'Discard any number of Victory cards, revealed.\n+ $2 per card discarded.',
    font_size: 'medium',
    cost: { coins: 7 },
    types: [CardType.ACTION, CardType.VICTORY, CardType.CASTLE],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Overlord',
    category: CardCategory.CARD,
    text: 'Play a non-Command non-Duration Action card from the Supply costing up to $5 , leaving it there.',
    font_size: 'medium',
    cost: { coins: 0, debt: 8 },
    types: [CardType.ACTION, CardType.COMMAND],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Patrician',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action Reveal the top card of your deck.\nIf it costs $5 or more, put it into your hand.',
    font_size: 'medium',
    cost: { coins: 2 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Plunder',
    category: CardCategory.CARD,
    text: '$2 +1',
    font_size: 'xxlarge',
    cost: { coins: 5 },
    types: [CardType.TREASURE],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Rocks',
    category: CardCategory.CARD,
    text: '$1',
    font_size: 'xxlarge',
    cost: { coins: 4 },
    types: [CardType.TREASURE],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Royal Blacksmith',
    category: CardCategory.CARD,
    text: '+5 Cards Reveal your hand; discard the Coppers.',
    font_size: 'large',
    cost: { coins: 0, debt: 8 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Sacrifice',
    category: CardCategory.CARD,
    text: "Trash a card from your hand.\nIf it's an… Action card,\n+2 Cards and\n+2 Actions Treasure card,\n+ $2 Victory card, +2",
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Settlers',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action You may reveal a Copper from your discard pile and put it into your hand.',
    font_size: 'medium',
    cost: { coins: 2 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Small Castle',
    category: CardCategory.CARD,
    text: 'Trash this or a Castle from your hand.\nIf you do, gain a Castle.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.VICTORY, CardType.CASTLE],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Sprawling Castle',
    category: CardCategory.CARD,
    text: '4',
    font_size: 'xxlarge',
    cost: { coins: 8 },
    types: [CardType.VICTORY, CardType.CASTLE],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Temple',
    category: CardCategory.CARD,
    text: '+1 Trash from 1 to 3 differently named cards from your hand. Add 1 to the Temple pile.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [CardType.ACTION, CardType.GATHERING],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Villa',
    category: CardCategory.CARD,
    text: '+2 Actions\n+1 Buy\n+ $1',
    font_size: 'xlarge',
    cost: { coins: 4 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Wild Hunt',
    category: CardCategory.CARD,
    text: 'Choose one:\n+3 Cards and add 1 to the Wild Hunt pile; or gain an Estate, and if you do, take the from the pile.',
    font_size: 'medium',
    cost: { coins: 5 },
    types: [CardType.ACTION, CardType.GATHERING],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Advance',
    category: CardCategory.EVENT,
    text: 'You may trash an Action card from your hand.\nIf you do, gain an Action card costing up to $6 .',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Annex',
    category: CardCategory.EVENT,
    text: 'Look through your discard pile. Shuffle all but up to 5 cards from it into your deck. Gain a Duchy.',
    font_size: 'medium',
    cost: { coins: 0, debt: 8 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Banquet',
    category: CardCategory.EVENT,
    text: 'Gain 2 Coppers and a non-Victory card costing up to $5 .',
    font_size: 'large',
    cost: { coins: 3 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Conquest',
    category: CardCategory.EVENT,
    text: "Gain 2 Silvers. +1 per Silver you've gained this turn.",
    font_size: 'large',
    cost: { coins: 6 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Delve',
    category: CardCategory.EVENT,
    text: '+1 Buy Gain a Silver.',
    font_size: 'xlarge',
    cost: { coins: 2 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Dominate',
    category: CardCategory.EVENT,
    text: 'Gain a Province.\nIf you do, +9 .',
    font_size: 'large',
    cost: { coins: 14 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Donate',
    category: CardCategory.EVENT,
    text: 'At the start of your next turn, first, put your deck and discard pile into your hand, trash any number of cards from it, then shuffle the rest into your deck and draw 5 cards.',
    font_size: 'medium',
    cost: { coins: 0, debt: 8 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Ritual',
    category: CardCategory.EVENT,
    text: 'Gain a Curse.\nIf you do, trash a card from your hand. +1 per $1 it costs.',
    font_size: 'medium',
    cost: { coins: 4 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Salt the Earth',
    category: CardCategory.EVENT,
    text: '+1 Trash a Victory card from the Supply.',
    font_size: 'large',
    cost: { coins: 4 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Tax',
    category: CardCategory.EVENT,
    text: 'Add 2D to a Supply pile.',
    font_size: 'xlarge',
    cost: { coins: 2 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Triumph',
    category: CardCategory.EVENT,
    text: "Gain an Estate.\nIf you did, +1 per card you've gained this turn.",
    font_size: 'medium',
    cost: { coins: 0, debt: 5 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Wedding',
    category: CardCategory.EVENT,
    text: '+1 Gain a Gold.',
    font_size: 'xlarge',
    cost: { coins: 4, debt: 3 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Windfall',
    category: CardCategory.EVENT,
    text: 'If your deck and discard pile are empty, gain 3 Golds.',
    font_size: 'large',
    cost: { coins: 5 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Aqueduct',
    category: CardCategory.LANDMARK,
    text: 'When you gain a Treasure, move 1 from its pile to this.\nWhen you gain a Victory card, take the from this.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Arena',
    category: CardCategory.LANDMARK,
    text: 'At the start of your Buy phase, you may discard an Action card.\nIf you do, take 2 from here.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Bandit Fort',
    category: CardCategory.LANDMARK,
    text: 'When scoring, -2 for each Silver and each Gold you have.',
    font_size: 'large',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Basilica',
    category: CardCategory.LANDMARK,
    text: 'When you gain a card in your Buy phase, if you have $2 or more, take 2 from here.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Baths',
    category: CardCategory.LANDMARK,
    text: 'When you end your turn without having gained a card, take 2 from here.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Battlefield',
    category: CardCategory.LANDMARK,
    text: 'When you gain a Victory card, take 2 from here.',
    font_size: 'large',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Colonnade',
    category: CardCategory.LANDMARK,
    text: 'When you gain an Action card in your Buy phase, if you have a copy of it in play, take 2 from here.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Defiled Shrine',
    category: CardCategory.LANDMARK,
    text: 'When you gain an Action, move 1 from its pile to this.\nWhen you gain a Curse in your Buy phase, take the from this.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Fountain',
    category: CardCategory.LANDMARK,
    text: 'When scoring, 15 if you have at least 10 Coppers.',
    font_size: 'large',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Keep',
    category: CardCategory.LANDMARK,
    text: 'When scoring, 5 per differently named Treasure you have, that you have more copies of than each other player, or tied for most.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Labyrinth',
    category: CardCategory.LANDMARK,
    text: 'When you gain a 2nd card in one of your turns, take 2 from here.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Mountain Pass',
    category: CardCategory.LANDMARK,
    text: 'When you are the first player to gain a Province, each player bids once, up to 40D , ending with you. High bidder gets +8 and takes the D they bid.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Museum',
    category: CardCategory.LANDMARK,
    text: 'When scoring, 2 per differently named card you have.',
    font_size: 'large',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Obelisk',
    category: CardCategory.LANDMARK,
    text: 'When scoring, 2 per card you have from the chosen pile.',
    font_size: 'large',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Orchard',
    category: CardCategory.LANDMARK,
    text: 'When scoring, 4 per differently named Action card you have 3 or more copies of.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Palace',
    category: CardCategory.LANDMARK,
    text: 'When scoring, 3 per set you have of Copper - Silver - Gold.',
    font_size: 'large',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Tomb',
    category: CardCategory.LANDMARK,
    text: 'When you trash a card, +1 .',
    font_size: 'xlarge',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Tower',
    category: CardCategory.LANDMARK,
    text: 'When scoring, 1 per non-Victory card you have from an empty Supply pile.',
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Triumphal Arch',
    category: CardCategory.LANDMARK,
    text: "When scoring, 3 per copy you have of the 2nd most common Action card among your cards (if it's a tie, count either).",
    font_size: 'medium',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Wall',
    category: CardCategory.LANDMARK,
    text: 'When scoring, -1 per card you have after the first 15.',
    font_size: 'large',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Wolf Den',
    category: CardCategory.LANDMARK,
    text: 'When scoring, -3 per card you have exactly one copy of.',
    font_size: 'large',
    cost: { coins: 0 },
    types: [],
    expansion: Expansion.EMPIRES,
    has_randomizer: false,
  },
  {
    name: 'Castles',
    category: CardCategory.RANDOMIZER_ONLY,
    text: 'Sort the Castle pile by cost,\nputting the more expensive\nCastles on the bottom. For a\n2-player game, use only one of\neach Castle. Only the top card\nof the pile can be\ngained or bought.',
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.VICTORY, CardType.CASTLE],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Catapult/Rocks',
    category: CardCategory.RANDOMIZER_ONLY,
    text: 'This pile starts the game with 5\ncopies of Catapult on top, then\n5 copies of Rocks.\nOnly the top card of the pile\ncan be gained or bought.',
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Encampment/Plunder',
    category: CardCategory.RANDOMIZER_ONLY,
    text: 'This pile starts the game with 5\ncopies of Encampment on top,\nthen 5 copies of Plunder. Only\nthe top card of the pile\ncan be gained or bought.',
    font_size: 'medium',
    cost: { coins: 2 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Gladiator/Fortune',
    category: CardCategory.RANDOMIZER_ONLY,
    text: 'This pile starts the game with 5\ncopies of Gladiator on top,\nthen 5 copies of Fortune. Only\nthe top card of the pile can be\ngained or bought.',
    font_size: 'medium',
    cost: { coins: 3 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Patrician/Emporium',
    category: CardCategory.RANDOMIZER_ONLY,
    text: 'This pile starts the game with 5\ncopies of Patrician on top, then\n5 copies of Emporium. Only\nthe top card of the pile can be\ngained or bought.',
    font_size: 'medium',
    cost: { coins: 2 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
  {
    name: 'Settlers/Bustling Village',
    category: CardCategory.RANDOMIZER_ONLY,
    text: 'This pile starts the game with 5\ncopies of Settlers on top, then\n5 copies of Bustling Village.\nOnly the top card of the pile\ncan be gained or bought.',
    font_size: 'medium',
    cost: { coins: 2 },
    types: [CardType.ACTION],
    expansion: Expansion.EMPIRES,
    has_randomizer: true,
  },
];
