import { CardCategory, CardInfo, CardType, Expansion, Mechanic } from '@dominion/common';

export const menagerie: CardInfo[] = [
  {
    name: 'Animal Fair',
    category: CardCategory.CARD,
    text: '+ $4\n+1 Buy per empty supply pile.',
    font_size: 'large',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Barge',
    category: CardCategory.CARD,
    text: 'Either now or at the start of your next turn,\n+3 Cards and\n+1 Buy .',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Black Cat',
    category: CardCategory.CARD,
    text: '+2 Cards If it isn\'t your turn, each other player gains a Curse.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.ATTACK, CardType.REACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Bounty Hunter',
    category: CardCategory.CARD,
    text: '+1 Action Exile a card from your hand.\nIf you didn\'t have a copy of it in Exile,\n+ $3 .',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Camel Train',
    category: CardCategory.CARD,
    text: 'Exile a non-Victory card from the Supply.',
    font_size: 'large',
    cost: {coins: 3},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Cardinal',
    category: CardCategory.CARD,
    text: '+ $2 Each other player reveals the top 2 cards of their deck, Exiles one costing from $3 to $6 , and discards the rest.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Cavalry',
    category: CardCategory.CARD,
    text: 'Gain 2 Horses.',
    font_size: 'xxlarge',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Coven',
    category: CardCategory.CARD,
    text: '+1 Action\n+ $2 Each other player Exiles a Curse from the Supply.\nIf they can\'t, they discard their Exiled Curses.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Destrier',
    category: CardCategory.CARD,
    text: '+2 Cards\n+1 Action',
    font_size: 'xlarge',
    cost: {coins: 6, has_asterisk: true},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Displace',
    category: CardCategory.CARD,
    text: 'Exile a card from your hand. Gain a differently named card costing up to $2 more than it.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Falconer',
    category: CardCategory.CARD,
    text: 'Gain a card to your hand costing less than this.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.REACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Fisherman',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n+ $1',
    font_size: 'xlarge',
    cost: {coins: 5, has_asterisk: true},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Gatekeeper',
    category: CardCategory.CARD,
    text: 'At the start of your next turn,\n+ $3 .\nUntil then, when another player gains an Action or Treasure card they don\'t have an Exiled copy of, they Exile it.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION, CardType.ATTACK],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Goatherd',
    category: CardCategory.CARD,
    text: '+1 Action You may trash a card from your hand.\n+1 Card per card the player to your right trashed on their last turn.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Groom',
    category: CardCategory.CARD,
    text: 'Gain a card costing up to $4 .\nIf it\'s an… Action card, gain a Horse; Treasure card, gain a Silver; Victory card,\n+1 Card and\n+1 Action .',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Hostelry',
    category: CardCategory.CARD,
    text: '+1 Card\n+2 Actions',
    font_size: 'xlarge',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Hunting Lodge',
    category: CardCategory.CARD,
    text: '+1 Card\n+2 Actions You may discard your hand for\n+5 Cards .',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Kiln',
    category: CardCategory.CARD,
    text: '+ $2 The next time you play a card this turn, you may first gain a copy of it.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Livery',
    category: CardCategory.CARD,
    text: '+ $3 This turn, when you gain a card costing $4 or more, gain a Horse.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Mastermind',
    category: CardCategory.CARD,
    text: 'At the start of your next turn, you may play an Action card from your hand three times.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Paddock',
    category: CardCategory.CARD,
    text: '+ $2 Gain 2 Horses.\n+1 Action per empty Supply pile.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Sanctuary',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action\n+1 Buy You may Exile a card from your hand.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Scrap',
    category: CardCategory.CARD,
    text: 'Trash a card from your hand. Choose a different thing per $1 it costs:\n+1 Card ;\n+1 Action ;\n+1 Buy ;\n+ $1 ; gain a Silver; gain a Horse.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Sheepdog',
    category: CardCategory.CARD,
    text: '+2 Cards',
    font_size: 'xxlarge',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.REACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Sleigh',
    category: CardCategory.CARD,
    text: 'Gain 2 Horses.',
    font_size: 'xxlarge',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.REACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Snowy Village',
    category: CardCategory.CARD,
    text: '+1 Card\n+4 Actions\n+1 Buy Ignore any further +Actions you get this turn.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Stockpile',
    category: CardCategory.CARD,
    text: '$3\n+1 Buy Exile this.',
    font_size: 'xlarge',
    cost: {coins: 3},
    types: [CardType.TREASURE],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Supplies',
    category: CardCategory.CARD,
    text: '$1 Gain a Horse onto your deck.',
    font_size: 'large',
    cost: {coins: 2},
    types: [CardType.TREASURE],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Village Green',
    category: CardCategory.CARD,
    text: 'Either now or at the start of your next turn,\n+1 Card and\n+2 Actions .',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.DURATION, CardType.REACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Wayfarer',
    category: CardCategory.CARD,
    text: '+3 Cards You may gain a Silver.',
    font_size: 'large',
    cost: {coins: 6, has_asterisk: true},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: true,
  },
  {
    name: 'Horse',
    category: CardCategory.CARD,
    text: '+2 Cards\n+1 Action Return this to its pile. (This is not in the Supply.)',
    font_size: 'medium',
    cost: {coins: 3, has_asterisk: true},
    types: [CardType.ACTION],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Alliance',
    category: CardCategory.EVENT,
    text: 'Gain a Province, a Duchy, an Estate, a Gold, a Silver, and a Copper.',
    font_size: 'medium',
    cost: {coins: 10},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Banish',
    category: CardCategory.EVENT,
    text: 'Exile any number of cards with the same name from your hand.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Bargain',
    category: CardCategory.EVENT,
    text: 'Gain a non-Victory card costing up to $5 . Each other player gains a Horse.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Commerce',
    category: CardCategory.EVENT,
    text: 'Gain a Gold per differently named card you\'ve gained this turn.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Delay',
    category: CardCategory.EVENT,
    text: 'You may set aside an Action card from your hand.\nAt the start of your next turn, play it.',
    font_size: 'medium',
    cost: {coins: 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Demand',
    category: CardCategory.EVENT,
    text: 'Gain a Horse and a card costing up to $4 , both onto your deck.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Desperation',
    category: CardCategory.EVENT,
    text: 'Once per turn: You may gain a Curse.\nIf you do,\n+1 Buy and\n+ $2 .',
    font_size: 'medium',
    cost: {coins: 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Enclave',
    category: CardCategory.EVENT,
    text: 'Gain a Gold. Exile a Duchy from the Supply.',
    font_size: 'large',
    cost: {coins: 8},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Enhance',
    category: CardCategory.EVENT,
    text: 'You may trash a non-Victory card from your hand, to gain a card costing up to $2 more than it.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Gamble',
    category: CardCategory.EVENT,
    text: '+1 Buy Discard the top card of your deck.\nIf it\'s an Action or Treasure, you may play it.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Invest',
    category: CardCategory.EVENT,
    text: 'Exile an Action card from the Supply.\nWhile it\'s in Exile, when another player gains or Invests in a copy of it,\n+2 Cards .',
    font_size: 'medium',
    cost: {coins: 4},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'March',
    category: CardCategory.EVENT,
    text: 'Look through your discard pile. You may play an Action card from it.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Populate',
    category: CardCategory.EVENT,
    text: 'Gain one card from each Action Supply pile.',
    font_size: 'large',
    cost: {coins: 10},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Pursue',
    category: CardCategory.EVENT,
    text: '+1 Buy Name a card. Reveal the top 4 cards from your deck. Put the matches back and discard the rest.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Reap',
    category: CardCategory.EVENT,
    text: 'Gain a Gold, setting it aside.\nAt the start of your next turn, play it.',
    font_size: 'medium',
    cost: {coins: 7},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Ride',
    category: CardCategory.EVENT,
    text: 'Gain a Horse.',
    font_size: 'xxlarge',
    cost: {coins: 2},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Seize the Day',
    category: CardCategory.EVENT,
    text: 'Once per game: Take an extra turn after this one.',
    font_size: 'large',
    cost: {coins: 4},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Stampede',
    category: CardCategory.EVENT,
    text: 'If you have 5 or fewer cards in play, gain 5 Horses onto your deck.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Toil',
    category: CardCategory.EVENT,
    text: '+1 Buy You may play an Action card from your hand.',
    font_size: 'large',
    cost: {coins: 2},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Transport',
    category: CardCategory.EVENT,
    text: 'Choose one: Exile an Action card from the Supply; or put an Action card you have in Exile onto your deck.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Butterfly',
    category: CardCategory.WAY,
    text: 'You may return this to its pile to gain a card costing exactly $1 more than it.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Camel',
    category: CardCategory.WAY,
    text: 'Exile a Gold from the Supply.',
    font_size: 'xlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Chameleon',
    category: CardCategory.WAY,
    text: 'Follow this card\'s instructions; each time that would give you +Cards this turn, you get + $ instead, and vice-versa.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Frog',
    category: CardCategory.WAY,
    text: '+1 Action When you discard this from play this turn, put it onto your deck.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Goat',
    category: CardCategory.WAY,
    text: 'Trash a card from your hand.',
    font_size: 'xlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Horse',
    category: CardCategory.WAY,
    text: '+2 Cards\n+1 Action Return this to its pile.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Mole',
    category: CardCategory.WAY,
    text: '+1 Action Discard your hand.\n+3 Cards .',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Monkey',
    category: CardCategory.WAY,
    text: '+1 Buy\n+ $1',
    font_size: 'xxlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Mouse',
    category: CardCategory.WAY,
    text: 'Play the set-aside card, leaving it there.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Mule',
    category: CardCategory.WAY,
    text: '+1 Action\n+ $1',
    font_size: 'xxlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Otter',
    category: CardCategory.WAY,
    text: '+2 Cards',
    font_size: 'xxlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Ox',
    category: CardCategory.WAY,
    text: '+2 Actions',
    font_size: 'xxlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Owl',
    category: CardCategory.WAY,
    text: 'Draw until you have 6 cards in hand.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Pig',
    category: CardCategory.WAY,
    text: '+1 Card\n+1 Action',
    font_size: 'xlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Rat',
    category: CardCategory.WAY,
    text: 'You may discard a Treasure to gain a copy of this.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Seal',
    category: CardCategory.WAY,
    text: '+ $1 This turn, when you gain a card, you may put it onto your deck.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Sheep',
    category: CardCategory.WAY,
    text: '+ $2',
    font_size: 'xxlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Squirrel',
    category: CardCategory.WAY,
    text: '+2 Cards at the end of this turn.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Turtle',
    category: CardCategory.WAY,
    text: 'Set this aside.\nIf you did, play it at the start of your next turn.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
  {
    name: 'Way of the Worm',
    category: CardCategory.WAY,
    text: 'Exile an Estate from the Supply.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.MENAGERIE,
    is_kingdom: false,
  },
];