import { CardCategory, CardInfo, CardType, Expansion, Mechanic } from '@dominion/common';

export const nocturne: CardInfo[] = [
  {
    name: 'Bard',
    category: CardCategory.CARD,
    text: '+ $2 Receive a Boon.',
    font_size: 'xlarge',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.FATE],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Blessed Village',
    category: CardCategory.CARD,
    text: '+1 Card\n+2 Actions',
    font_size: 'xlarge',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.FATE],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Cemetery',
    category: CardCategory.CARD,
    text: '2',
    font_size: 'xxlarge',
    cost: {coins: 4},
    types: [CardType.VICTORY],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Changeling',
    category: CardCategory.CARD,
    text: 'Trash this. Gain a copy of a card you have in play.',
    font_size: 'large',
    cost: {coins: 3},
    types: [CardType.NIGHT],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Cobbler',
    category: CardCategory.CARD,
    text: 'At the start of your next turn, gain a card to your hand costing up to $4 .',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.NIGHT, CardType.DURATION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Conclave',
    category: CardCategory.CARD,
    text: '+ $2 You may play an Action card from your hand that you don\'t have a copy of in play.\nIf you do,\n+1 Action .',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Crypt',
    category: CardCategory.CARD,
    text: 'Set aside any number of non-Duration Treasures you have in play, face down (under this).\nWhile any remain, at the start of each of your turns, put one of them into your hand.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.NIGHT, CardType.DURATION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Cursed Village',
    category: CardCategory.CARD,
    text: '+2 Actions Draw until you have 6 cards in hand.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Den of Sin',
    category: CardCategory.CARD,
    text: 'At the start of your next turn,\n+2 Cards.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.NIGHT, CardType.DURATION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Devil\'s Workshop',
    category: CardCategory.CARD,
    text: 'If the number of cards you\'ve gained this turn is: 2+, gain an Imp; 1, gain a card costing up to $4 ; 0, gain a Gold.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.NIGHT],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Druid',
    category: CardCategory.CARD,
    text: '+1 Buy Receive one of the set-aside Boons (leaving it there).',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.FATE],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Exorcist',
    category: CardCategory.CARD,
    text: 'Trash a card from your hand. Gain a cheaper Spirit from one of the Spirit piles.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.NIGHT],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Faithful Hound',
    category: CardCategory.CARD,
    text: '+2 Cards',
    font_size: 'xxlarge',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.REACTION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Fool',
    category: CardCategory.CARD,
    text: 'If you aren\'t the player with Lost in the Woods: take it, take 3 Boons, and receive the Boons in any order.\nHeirloom: Lucky Coin',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.FATE],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Ghost Town',
    category: CardCategory.CARD,
    text: 'At the start of your next turn,\n+1 Card and\n+1 Action .',
    font_size: 'large',
    cost: {coins: 3},
    types: [CardType.NIGHT, CardType.DURATION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Guardian',
    category: CardCategory.CARD,
    text: 'At the start of your next turn,\n+ $1 .\nUntil then, when another player plays an Attack card, it doesn\'t affect you.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.NIGHT, CardType.DURATION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Idol',
    category: CardCategory.CARD,
    text: '$2 If you have an odd number of Idols in play (counting this), receive a Boon; otherwise, each other player gains a Curse.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.TREASURE, CardType.ATTACK, CardType.FATE],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Leprechaun',
    category: CardCategory.CARD,
    text: 'Gain a Gold.\nIf you have exactly 7 cards in play, gain a Wish. Otherwise, receive a Hex.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.DOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Monastery',
    category: CardCategory.CARD,
    text: 'For each card you\'ve gained this turn, you may trash a card from your hand or a Copper you have in play.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.NIGHT],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Necromancer',
    category: CardCategory.CARD,
    text: 'Choose a face up, non-Duration Action card in the trash. Turn it face down for the turn, and play it, leaving it there.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Night Watchman',
    category: CardCategory.CARD,
    text: 'Look at the top 5 cards of your deck, discard any number, and put the rest back in any order.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.NIGHT],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Pixie',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action Discard the top Boon. You may trash this to receive that Boon twice.\nHeirloom: Goat',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.FATE],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Pooka',
    category: CardCategory.CARD,
    text: 'You may trash a Treasure other than Cursed Gold from your hand, for\n+4 Cards .\nHeirloom: Cursed Gold',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Raider',
    category: CardCategory.CARD,
    text: 'Each other player with 5 or more cards in hand discards a copy of a card you have in play (or reveals they can\'t).\nAt the start of your next turn,\n+ $3 .',
    font_size: 'medium',
    cost: {coins: 6},
    types: [CardType.NIGHT, CardType.DURATION, CardType.ATTACK],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Sacred Grove',
    category: CardCategory.CARD,
    text: '+1 Buy\n+ $3 Receive a Boon.\nIf it doesn\'t give\n+ $1 , each other player may receive it.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.FATE],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Secret Cave',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action You may discard 3 cards.\nIf you did, then at the start of your next turn,\n+ $3 .\nHeirloom: Magic Lamp',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Shepherd',
    category: CardCategory.CARD,
    text: '+1 Action Discard any number of Victory cards, revealing them.\n+2 Cards per card discarded.\nHeirloom: Pasture',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Skulk',
    category: CardCategory.CARD,
    text: '+1 Buy Each other player receives the next Hex.',
    font_size: 'large',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.ATTACK, CardType.DOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Tormentor',
    category: CardCategory.CARD,
    text: '+ $2 If you have no other cards in play, gain an Imp. Otherwise, each other player receives the next Hex.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.ATTACK, CardType.DOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Tracker',
    category: CardCategory.CARD,
    text: '+ $1 This turn, when you gain a card, you may put it onto your deck. Receive a Boon.\nHeirloom: Pouch',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.FATE],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Tragic Hero',
    category: CardCategory.CARD,
    text: '+3 Cards\n+1 Buy If you have 8 or more cards in hand (after drawing), trash this and gain a Treasure.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Vampire',
    category: CardCategory.CARD,
    text: 'Each other player receives the next Hex. Gain a card costing up to $5 other than a Vampire. Exchange this for a Bat.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.NIGHT, CardType.ATTACK, CardType.DOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Werewolf',
    category: CardCategory.CARD,
    text: 'If it\'s your Night phase, each other player receives the next Hex. Otherwise,\n+3 Cards .',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.NIGHT, CardType.ATTACK, CardType.DOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: true,
  },
  {
    name: 'Bat',
    category: CardCategory.CARD,
    text: 'Trash up to 2 cards from your hand.\nIf you trashed at least one, exchange this for a Vampire. (This is not in the Supply.)',
    font_size: 'medium',
    cost: {coins: 2, has_asterisk: true},
    types: [CardType.NIGHT],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Cursed Gold',
    category: CardCategory.CARD,
    text: '$3 Gain a Curse.',
    font_size: 'xlarge',
    cost: {coins: 4},
    types: [CardType.TREASURE, CardType.HEIRLOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Ghost',
    category: CardCategory.CARD,
    text: 'Reveal cards from your deck until you reveal an Action. Discard the other cards and set aside the Action.\nAt the start of your next turn, play it twice. (This is not in the Supply.)',
    font_size: 'small',
    cost: {coins: 4, has_asterisk: true},
    types: [CardType.NIGHT, CardType.DURATION, CardType.SPIRIT],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Goat',
    category: CardCategory.CARD,
    text: '$1 You may trash a card from your hand.',
    font_size: 'large',
    cost: {coins: 2},
    types: [CardType.TREASURE, CardType.HEIRLOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Haunted Mirror',
    category: CardCategory.CARD,
    text: '$1',
    font_size: 'xxlarge',
    cost: {coins: 0},
    types: [CardType.TREASURE, CardType.HEIRLOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Imp',
    category: CardCategory.CARD,
    text: '+2 Cards You may play an Action card from your hand that you don\'t have a copy of in play. (This is not in the Supply.)',
    font_size: 'medium',
    cost: {coins: 2, has_asterisk: true},
    types: [CardType.ACTION, CardType.SPIRIT],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Lucky Coin',
    category: CardCategory.CARD,
    text: '$1 Gain a Silver.',
    font_size: 'xlarge',
    cost: {coins: 4},
    types: [CardType.TREASURE, CardType.HEIRLOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Magic Lamp',
    category: CardCategory.CARD,
    text: '$1 If there are at least 6 cards that you have exactly 1 copy of in play (counting this), trash this.\nIf you did, gain 3 Wishes.',
    font_size: 'medium',
    cost: {coins: 0},
    types: [CardType.TREASURE, CardType.HEIRLOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Pasture',
    category: CardCategory.CARD,
    text: '$1',
    font_size: 'xxlarge',
    cost: {coins: 2},
    types: [CardType.TREASURE, CardType.VICTORY, CardType.HEIRLOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Pouch',
    category: CardCategory.CARD,
    text: '$1\n+1 Buy',
    font_size: 'xxlarge',
    cost: {coins: 2},
    types: [CardType.TREASURE, CardType.HEIRLOOM],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Will-o\'-Wisp',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action Reveal the top card of your deck.\nIf it costs $2 or less, put it into your hand. (This is not in the Supply.)',
    font_size: 'medium',
    cost: {coins: 0, has_asterisk: true},
    types: [CardType.ACTION, CardType.SPIRIT],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Wish',
    category: CardCategory.CARD,
    text: '+1 Action Return this to its pile.\nIf you did, gain a card to your hand costing up to $6 . (This is not in the Supply.)',
    font_size: 'medium',
    cost: {coins: 0, has_asterisk: true},
    types: [CardType.ACTION],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Zombie Apprentice',
    category: CardCategory.CARD,
    text: 'You may trash an Action card from your hand for\n+3 Cards and\n+1 Action .',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.ZOMBIE],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Zombie Mason',
    category: CardCategory.CARD,
    text: 'Trash the top card of your deck. You may gain a card costing up to $1 more than it.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.ZOMBIE],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Zombie Spy',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action Look at the top card of your deck. Discard it or put it back.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.ZOMBIE],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The Earth\'s Gift',
    category: CardCategory.BOON,
    text: 'You may discard a Treasure to gain a card costing up to $4 .',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The Field\'s Gift',
    category: CardCategory.BOON,
    text: '+1 Action\n+ $1 (Keep this until Clean-up.)',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The Flame\'s Gift',
    category: CardCategory.BOON,
    text: 'You may trash a card from your hand.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The Forest\'s Gift',
    category: CardCategory.BOON,
    text: '+1 Buy\n+ $1 (Keep this until Clean-up.)',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The Moon\'s Gift',
    category: CardCategory.BOON,
    text: 'Look through your discard pile. You may put a card from it onto your deck.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The Mountain\'s Gift',
    category: CardCategory.BOON,
    text: 'Gain a Silver.',
    font_size: 'xxlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The River\'s Gift',
    category: CardCategory.BOON,
    text: '+1 Card at the end of this turn. (Keep this until Clean-up.)',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The Sea\'s Gift',
    category: CardCategory.BOON,
    text: '+1 Card',
    font_size: 'xxlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The Sky\'s Gift',
    category: CardCategory.BOON,
    text: 'You may discard 3 cards to gain a Gold.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The Sun\'s Gift',
    category: CardCategory.BOON,
    text: 'Look at the top 4 cards of your deck. Discard any number of them and put the rest back in any order.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The Swamp\'s Gift',
    category: CardCategory.BOON,
    text: 'Gain a Will-o\'-Wisp.',
    font_size: 'xlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'The Wind\'s Gift',
    category: CardCategory.BOON,
    text: '+2 Cards Discard 2 cards.',
    font_size: 'xlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Bad Omens',
    category: CardCategory.HEX,
    text: 'Put your deck into your discard pile. Look through it and put 2 Coppers from it onto your deck (or reveal you can\'t).',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Delusion',
    category: CardCategory.HEX,
    text: 'If you don\'t have Deluded or Envious, take Deluded.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Envy',
    category: CardCategory.HEX,
    text: 'If you don\'t have Deluded or Envious, take Envious.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Famine',
    category: CardCategory.HEX,
    text: 'Reveal the top 3 cards of your deck. Discard the Actions. Shuffle the rest into your deck.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Fear',
    category: CardCategory.HEX,
    text: 'If you have at least 5 cards in hand, discard an Action or Treasure (or reveal you can\'t).',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Greed',
    category: CardCategory.HEX,
    text: 'Gain a Copper onto your deck.',
    font_size: 'xlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Haunting',
    category: CardCategory.HEX,
    text: 'If you have at least 4 cards in hand, put one of them onto your deck.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Locusts',
    category: CardCategory.HEX,
    text: 'Trash the top card of your deck.\nIf it\'s Copper or Estate, gain a Curse. Otherwise, gain a cheaper card that shares a type with it.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Misery',
    category: CardCategory.HEX,
    text: 'If this is your first Misery this game, take Miserable. Otherwise, flip it over to Twice Miserable.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Plague',
    category: CardCategory.HEX,
    text: 'Gain a Curse to your hand.',
    font_size: 'xlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Poverty',
    category: CardCategory.HEX,
    text: 'Discard down to 3 cards in hand.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'War',
    category: CardCategory.HEX,
    text: 'Reveal cards from your deck until revealing one costing $3 or $4 . Trash it and discard the rest.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Deluded',
    category: CardCategory.STATE,
    text: 'At the start of your Buy phase, return this, and you can\'t buy Actions this turn.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Envious',
    category: CardCategory.STATE,
    text: 'At the start of your Buy phase, return this, and Silver and Gold make $1 this turn.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Lost in the Woods',
    category: CardCategory.STATE,
    text: 'At the start of your turn, you may discard a card to receive a Boon.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Miserable',
    category: CardCategory.STATE,
    text: '-2',
    font_size: 'xxlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
  {
    name: 'Twice Miserable',
    category: CardCategory.STATE,
    text: '-4',
    font_size: 'xxlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.NOCTURNE,
    is_kingdom: false,
  },
];