import { CardCategory, CardInfo, CardType, Expansion, Mechanic } from '@dominion/common';

export const plunder: CardInfo[] = [
  {
    name: 'Abundance',
    category: CardCategory.CARD,
    text: 'The next time you gain an Action card:\n+1 Buy and\n+ $3 .',
    font_size: 'large',
    cost: {coins: 4},
    types: [CardType.TREASURE, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Buried Treasure',
    category: CardCategory.CARD,
    text: 'At the start of your next turn,\n+1 Buy and\n+ $3 .',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.TREASURE, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Cabin Boy',
    category: CardCategory.CARD,
    text: '+1 Card\n+1 Action At the start of your next turn, choose one:\n+ $2 ; or trash this to gain a Duration card.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Cage',
    category: CardCategory.CARD,
    text: 'Set aside up to 4 cards from your hand face down (on this). The next time you gain a Victory card, trash this, and put the set aside cards into your hand at end of turn.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.TREASURE, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Crew',
    category: CardCategory.CARD,
    text: '+3 Cards At the start of your next turn, put this onto your deck.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Crucible',
    category: CardCategory.CARD,
    text: 'Trash a card from your hand.\n+ $1 per $1 it costs.',
    font_size: 'large',
    cost: {coins: 4},
    types: [CardType.TREASURE],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Cutthroat',
    category: CardCategory.CARD,
    text: 'Each other player discards down to 3 cards in hand. The next time anyone gains a Treasure costing $5 or more, gain a Loot.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION, CardType.ATTACK],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Enlarge',
    category: CardCategory.CARD,
    text: 'Now and at the start of your next turn: Trash a card from your hand, and gain one costing up to $2 more.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Figurine',
    category: CardCategory.CARD,
    text: '+2 Cards You may discard an Action card for\n+1 Buy and\n+ $1 .',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.TREASURE],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'First Mate',
    category: CardCategory.CARD,
    text: 'Play any number of Action cards with the same name from your hand, then draw until you have 6 cards in hand.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Flagship',
    category: CardCategory.CARD,
    text: '+ $2 The next time you play a non-Command Action card, replay it.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.DURATION, CardType.COMMAND],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Fortune Hunter',
    category: CardCategory.CARD,
    text: '+ $2 Look at the top 3 cards of your deck. You may play a Treasure from them. Put the rest back in any order.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Frigate',
    category: CardCategory.CARD,
    text: '+ $3 Until the start of your next turn, each time another player plays an Action card, they discard down to 4 cards in hand afterwards.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION, CardType.ATTACK],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Gondola',
    category: CardCategory.CARD,
    text: 'Either now or at the start of your next turn:\n+ $2 .',
    font_size: 'large',
    cost: {coins: 4},
    types: [CardType.TREASURE, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Grotto',
    category: CardCategory.CARD,
    text: '+1 Action Set aside up to 4 cards from your hand face down (on this).\nAt the start of your next turn, discard them, then draw as many.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Harbor Village',
    category: CardCategory.CARD,
    text: '+1 Card\n+2 Actions After the next Action you play this turn, if it gave you + $ ,\n+ $1 .',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Jewelled Egg',
    category: CardCategory.CARD,
    text: '$1\n+1 Buy',
    font_size: 'xxlarge',
    cost: {coins: 2},
    types: [CardType.TREASURE],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'King\'s Cache',
    category: CardCategory.CARD,
    text: 'You may play a Treasure from your hand 3 times.',
    font_size: 'large',
    cost: {coins: 7},
    types: [CardType.TREASURE],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Landing Party',
    category: CardCategory.CARD,
    text: '+2 Cards\n+2 Actions The next time the first card you play on a turn is a Treasure, put this onto your deck afterwards.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Longship',
    category: CardCategory.CARD,
    text: '+2 Actions At the start of your next turn,\n+2 Cards .',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Mapmaker',
    category: CardCategory.CARD,
    text: 'Look at the top 4 cards of your deck. Put 2 into your hand and discard the rest.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION, CardType.REACTION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Maroon',
    category: CardCategory.CARD,
    text: 'Trash a card from your hand.\n+2 Cards per type it has (Action, Attack, etc.).',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Mining Road',
    category: CardCategory.CARD,
    text: '+1 Action\n+1 Buy\n+ $2 Once this turn, when you gain a Treasure, you may play it.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Pendant',
    category: CardCategory.CARD,
    text: '+ $1 per differently named Treasure you have in play.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.TREASURE],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Pickaxe',
    category: CardCategory.CARD,
    text: '$1 Trash a card from your hand.\nIf it costs $3 or more, gain a Loot to your hand.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.TREASURE],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Pilgrim',
    category: CardCategory.CARD,
    text: '+4 Cards Put a card from your hand onto your deck.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Quartermaster',
    category: CardCategory.CARD,
    text: 'At the start of each of your turns for the rest of the game, choose one: Gain a card costing up to $4 , setting it aside on this; or put a card from this into your hand.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Rope',
    category: CardCategory.CARD,
    text: '$1\n+1 Buy At the start of your next turn,\n+1 Card and you may trash a card from your hand.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.TREASURE, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Sack of Loot',
    category: CardCategory.CARD,
    text: '$1\n+1 Buy Gain a Loot.',
    font_size: 'xlarge',
    cost: {coins: 6},
    types: [CardType.TREASURE],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Search',
    category: CardCategory.CARD,
    text: '+ $2 The next time a Supply pile empties, trash this and gain a Loot.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Secluded Shrine',
    category: CardCategory.CARD,
    text: '+ $1 The next time you gain a Treasure, trash up to 2 cards from your hand.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Shaman',
    category: CardCategory.CARD,
    text: '+1 Action\n+ $1 You may trash a card from your hand.',
    font_size: 'large',
    cost: {coins: 2},
    types: [CardType.ACTION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Silver Mine',
    category: CardCategory.CARD,
    text: 'Gain a Treasure costing less than this to your hand.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.TREASURE],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Siren',
    category: CardCategory.CARD,
    text: 'Each other player gains a Curse.\nAt the start of your next turn, draw until you have 8 cards in hand.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.DURATION, CardType.ATTACK],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Stowaway',
    category: CardCategory.CARD,
    text: 'At the start of your next turn,\n+2 Cards.',
    font_size: 'large',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.DURATION, CardType.REACTION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Swamp Shacks',
    category: CardCategory.CARD,
    text: '+2 Actions\n+1 Card per 3 cards you have in play (round down).',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Taskmaster',
    category: CardCategory.CARD,
    text: '+1 Action ,\n+ $1 , and if you gain a card costing exactly $5 this turn, then at the start of your next turn, repeat this ability.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Tools',
    category: CardCategory.CARD,
    text: 'Gain a copy of a card anyone has in play.',
    font_size: 'large',
    cost: {coins: 4},
    types: [CardType.TREASURE],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Trickster',
    category: CardCategory.CARD,
    text: 'Each other player gains a Curse. Once this turn, when you discard a Treasure from play, you may set it aside. Put it in your hand at end of turn.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.ACTION, CardType.ATTACK],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Wealthy Village',
    category: CardCategory.CARD,
    text: '+1 Card\n+2 Actions',
    font_size: 'xlarge',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Amphora',
    category: CardCategory.CARD,
    text: 'Either now or at the start of your next turn:\n+1 Buy and\n+ $3 .',
    font_size: 'medium',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.DURATION, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Doubloons',
    category: CardCategory.CARD,
    text: '$3',
    font_size: 'xxlarge',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Endless Chalice',
    category: CardCategory.CARD,
    text: 'Now and at the start of each of your turns for the rest of the game: $1\n+1 Buy',
    font_size: 'medium',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.DURATION, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Figurehead',
    category: CardCategory.CARD,
    text: '$3 At the start of your next turn,\n+2 Cards .',
    font_size: 'large',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.DURATION, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Hammer',
    category: CardCategory.CARD,
    text: '$3 Gain a card costing up to $4 .',
    font_size: 'large',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Insignia',
    category: CardCategory.CARD,
    text: '$3 This turn, when you gain a card, you may put it onto your deck.',
    font_size: 'medium',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Jewels',
    category: CardCategory.CARD,
    text: '$3\n+1 Buy At the start of your next turn, put this on the bottom of your deck.',
    font_size: 'medium',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.DURATION, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Orb',
    category: CardCategory.CARD,
    text: 'Look through your discard pile. Choose one: Play an Action or Treasure from it; or\n+1 Buy and\n+ $3 .',
    font_size: 'medium',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Prize Goat',
    category: CardCategory.CARD,
    text: '$3\n+1 Buy You may trash a card from your hand.',
    font_size: 'large',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Puzzle Box',
    category: CardCategory.CARD,
    text: '$3\n+1 Buy You may set aside a card from your hand face down. Put it into your hand at end of turn.',
    font_size: 'medium',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Sextant',
    category: CardCategory.CARD,
    text: '$3\n+1 Buy Look at the top 5 cards of your deck. Discard any number. Put the rest back in any order.',
    font_size: 'medium',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Shield',
    category: CardCategory.CARD,
    text: '$3\n+1 Buy',
    font_size: 'xxlarge',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.REACTION, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Spell Scroll',
    category: CardCategory.CARD,
    text: 'Trash this to gain a cheaper card.\nIf it\'s an Action or Treasure, you may play it.',
    font_size: 'medium',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.ACTION, CardType.TREASURE, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Staff',
    category: CardCategory.CARD,
    text: '$3\n+1 Buy You may play an Action from your hand.',
    font_size: 'large',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Sword',
    category: CardCategory.CARD,
    text: '$3\n+1 Buy Each other player discards down to 4 cards in hand.',
    font_size: 'medium',
    cost: {coins: 7, has_asterisk: true},
    types: [CardType.TREASURE, CardType.ATTACK, CardType.LOOT],
    expansion: Expansion.PLUNDER,
    is_kingdom: true,
  },
  {
    name: 'Avoid',
    category: CardCategory.EVENT,
    text: '+1 Buy The next time you shuffle this turn, pick up to 3 of those cards to put into your discard pile.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Bury',
    category: CardCategory.EVENT,
    text: '+1 Buy Put any card from your discard pile on the bottom of your deck.',
    font_size: 'medium',
    cost: {coins: 1},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Deliver',
    category: CardCategory.EVENT,
    text: '+1 Buy This turn, each time you gain a card, set it aside, and put it into your hand at end of turn.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Foray',
    category: CardCategory.EVENT,
    text: 'Discard 3 cards, revealing them.\nIf they have 3 different names, gain a Loot.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Invasion',
    category: CardCategory.EVENT,
    text: 'You may play an Attack from your hand. Gain a Duchy. Gain an Action onto your deck. Gain a Loot; play it.',
    font_size: 'medium',
    cost: {coins: 10},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Journey',
    category: CardCategory.EVENT,
    text: 'You don\'t discard cards from play in Clean-up this turn. Take an extra turn after this one (but not a 3rd turn in a row).',
    font_size: 'medium',
    cost: {coins: 4},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Launch',
    category: CardCategory.EVENT,
    text: 'Once per turn: Return to your Action phase.\n+1 Card ,\n+1 Action , and\n+1 Buy .',
    font_size: 'medium',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Looting',
    category: CardCategory.EVENT,
    text: 'Gain a Loot.',
    font_size: 'xxlarge',
    cost: {coins: 6},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Maelstrom',
    category: CardCategory.EVENT,
    text: 'Trash 3 cards from your hand. Each other player with 5 or more cards in hand trashes one of them.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Mirror',
    category: CardCategory.EVENT,
    text: '+1 Buy The next time you gain an Action card this turn, gain a copy of it.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Peril',
    category: CardCategory.EVENT,
    text: 'You may trash an Action card from your hand to gain a Loot.',
    font_size: 'large',
    cost: {coins: 2},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Prepare',
    category: CardCategory.EVENT,
    text: 'Set aside your hand face up.\nAt the start of your next turn, play those Actions and Treasures in any order, then discard the rest.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Prosper',
    category: CardCategory.EVENT,
    text: 'Gain a Loot, plus any number of differently named Treasures.',
    font_size: 'medium',
    cost: {coins: 10},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Rush',
    category: CardCategory.EVENT,
    text: '+1 Buy The next time you gain an Action card this turn, play it.',
    font_size: 'medium',
    cost: {coins: 2},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Scrounge',
    category: CardCategory.EVENT,
    text: 'Choose one: Trash a card from your hand; or gain an Estate from the trash, and if you did, gain a card costing up to $5 .',
    font_size: 'medium',
    cost: {coins: 3},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Cheap',
    category: CardCategory.TRAIT,
    text: 'Cheap cards cost $1 less.',
    font_size: 'xlarge',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Cursed',
    category: CardCategory.TRAIT,
    text: 'When you gain a Cursed card, gain a Loot and a Curse.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Fated',
    category: CardCategory.TRAIT,
    text: 'When shuffling, you may look through the cards and reveal Fated cards to put them on the top or bottom.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Fawning',
    category: CardCategory.TRAIT,
    text: 'When you gain a Province, gain a Fawning card.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Friendly',
    category: CardCategory.TRAIT,
    text: 'At the start of your Clean-up phase, you may discard a Friendly card to gain a Friendly card.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Hasty',
    category: CardCategory.TRAIT,
    text: 'When you gain a Hasty card, set it aside, and play it at the start of your next turn.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Inherited',
    category: CardCategory.TRAIT,
    text: 'Setup: You start the game with an Inherited card in place of a starting card you choose.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Inspiring',
    category: CardCategory.TRAIT,
    text: 'After playing an Inspiring card on your turn, you may play an Action from your hand that you don\'t have a copy of in play.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Nearby',
    category: CardCategory.TRAIT,
    text: 'When you gain a Nearby card,\n+1 Buy .',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Patient',
    category: CardCategory.TRAIT,
    text: 'At the start of your Clean-up phase, you may set aside Patient cards from your hand to play them at the start of your next turn.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Pious',
    category: CardCategory.TRAIT,
    text: 'When you gain a Pious card, you may trash a card from your hand.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Reckless',
    category: CardCategory.TRAIT,
    text: 'Follow the instructions of played Reckless cards twice.\nWhen discarding one from play, return it to its pile.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Rich',
    category: CardCategory.TRAIT,
    text: 'When you gain a Rich card, gain a Silver.',
    font_size: 'large',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Shy',
    category: CardCategory.TRAIT,
    text: 'At the start of your turn, you may discard one Shy card for\n+2 Cards .',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
  {
    name: 'Tireless',
    category: CardCategory.TRAIT,
    text: 'When you discard a Tireless card from play, set it aside, and put it onto your deck at end of turn.',
    font_size: 'medium',
    cost: {'coins': 0},
    types: [],
    expansion: Expansion.PLUNDER,
    is_kingdom: false,
  },
];