import { CardCategory, CardInfo, CardType, Expansion, Mechanic } from '@dominion/common';

export const promo: CardInfo[] = [
  {
    category: CardCategory.CARD,
    name: 'Avanto',
    text: '+3 Cards You may play a Sauna from your hand.',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Black Market',
    text: '+ $2 Reveal the top 3 cards of the Black Market deck. Play any number of Treasures from your hand. You may buy one of the revealed cards. Put the rest on the bottom of the Black Market deck in any order.',
    font_size: 'small',
    cost: {coins: 3},
    types: [CardType.ACTION],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Captain',
    text: 'Now and at the start of your next turn: Play a non-Duration, non-Command Action card from the Supply costing up to $4 , leaving it there.',
    font_size: 'medium',
    cost: {coins: 6},
    types: [CardType.ACTION, CardType.DURATION, CardType.COMMAND],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Church',
    text: '+1 Action Set aside up to 3 cards from your hand face down.\nAt the start of your next turn, put them into your hand, then you may trash a card from your hand.',
    font_size: 'medium',
    cost: {coins: 3},
    types: [CardType.ACTION, CardType.DURATION],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Dismantle',
    text: 'Trash a card from your hand.\nIf it costs $1 or more, gain a cheaper card and a Gold.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Envoy',
    text: 'Reveal the top 5 cards of your deck. The player to your left chooses one. Discard that one and put the rest into your hand.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Governor',
    text: '+1 Action Choose one; you get the version in parentheses: Each player gets +1 (+3) Cards ; or each player gains a Silver (Gold); or each player may trash a card from their hand and gain a card costing exactly $1 ( $2 ) more.',
    font_size: 'small',
    cost: {coins: 5},
    types: [CardType.ACTION],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Marchland',
    text: 'Worth 1 per 3 Victory cards you have (round down).',
    font_size: 'large',
    cost: {coins: 5},
    types: [CardType.VICTORY],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Prince',
    text: 'You may set aside (on this) a non-Duration, non-Command Action card from your hand costing up to $4 .\nAt the start of each of your turns, play that card, leaving it set aside.',
    font_size: 'medium',
    cost: {coins: 8},
    types: [CardType.ACTION, CardType.DURATION, CardType.COMMAND],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Sauna',
    text: '+1 Card\n+1 Action You may play an Avanto from your hand. This turn, when you play a Silver, you may trash a card from your hand.',
    font_size: 'medium',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
  {
    category: CardCategory.CARD,
    name: 'Stash',
    text: '$2 When shuffling this, you may look through your remaining deck, and may put this anywhere in the shuffled cards.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [CardType.TREASURE],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
  {
    category: CardCategory.EVENT,
    name: 'Summon',
    text: 'Gain an Action card costing up to $4 . Set it aside.\nIf you did, then at the start of your next turn, play it.',
    font_size: 'medium',
    cost: {coins: 5},
    types: [],
    expansion: Expansion.PROMO,
    is_kingdom: false,
  },
  {
    category: CardCategory.CARD,
    name: 'Walled Village',
    text: '+1 Card\n+2 Actions',
    font_size: 'xlarge',
    cost: {coins: 4},
    types: [CardType.ACTION],
    expansion: Expansion.PROMO,
    is_kingdom: true,
  },
];