export enum MessageType {
  LOG = 'log',
  CHAT = 'chat',
  DM = 'dm',
  PLAYER_NAME = 'player_name',
  OPPONENT_NAME = 'opponent_name',
  GAME_CONFIGURATION = 'game_configuration',
  TURN_START = 'turn_start',
  STATISTIC = 'statistic',
  CARDS = 'cards',
  CARD_COUNT = 'card_count',
  TOP_CARD = 'top_card',
  SHARED_CARDS = 'shared_cards',
  PILE_METADATA = 'pile_metadata',
  STATUS = 'status',
  CHOOSE_CARD = 'choose_card',
  CHOOSE_CARDS = 'choose_cards',
  CHOOSE_ONE_OPTION = 'choose_one_option',
  CHOOSE_MULTIPLE_OPTIONS = 'choose_multiple_options',
  CHOOSE_EFFECT = 'choose_effect',
  CHOOSE_EXTRA_TURN = 'choose_extra_turn',
  ACTION_PHASE_CHOICE = 'action_phase_choice',
  TREASURE_PHASE_CHOICE = 'treasure_phase_choice',
  BUY_PHASE_CHOICE = 'buy_phase_choice',
  RESOLVED_CHOICE = 'resolved_choice',
  GAME_RESULT = 'game_result',
}
